(function(){
  'use strict';
  if(location.pathname!=='/invoice-generator/'&&!location.pathname.startsWith('/invoice-generator/'))return;
  const lang=(()=>{try{const v=localStorage.getItem('sbk_language');return ['no','sv','de','es','fr'].includes(v)?v:'en'}catch(_){return'en'}})();
  if(lang==='en')return;

  const D={
    no:{
      'Free · private · no account required':'Gratis · privat · ingen konto nødvendig','Free Invoice Generator':'Gratis fakturagenerator','Create a professional invoice with multiple line items, tax, discounts, your logo, payment terms and notes. Your draft auto-saves locally in this browser, then you can print or save the invoice as a PDF.':'Lag en profesjonell faktura med flere varelinjer, skatt/MVA, rabatt, logo, betalingsvilkår og notater. Utkastet lagres lokalt i nettleseren, og du kan skrive ut eller lagre som PDF.','Free to use':'Gratis å bruke','No SoloBizKit account':'Ingen SoloBizKit-konto','Auto-saves locally':'Lagrer lokalt automatisk','Print or save as PDF':'Skriv ut eller lagre som PDF','New invoice':'Ny faktura','Duplicate':'Dupliser','Saved locally':'Lagret lokalt','Print / Save PDF':'Skriv ut / lagre PDF','Your business':'Din bedrift','Business name':'Bedriftsnavn','Logo (optional)':'Logo (valgfritt)','Email':'E-post','Phone':'Telefon','Business address':'Bedriftsadresse','Client & invoice details':'Kunde- og fakturadetaljer','Client / company':'Kunde / firma','Client email':'Kundens e-post','Client address':'Kundeadresse','Invoice #':'Fakturanr.','Issue date':'Fakturadato','Due date':'Forfallsdato','Currency':'Valuta','Payment terms':'Betalingsvilkår','Due on receipt':'Forfaller ved mottak','Line items':'Varelinjer','+ Add line item':'+ Legg til linje','Totals & notes':'Summer og notater','Tax %':'MVA / skatt %','Discount %':'Rabatt %','Notes / payment instructions':'Notater / betalingsinstruksjoner','Invoice':'Faktura','From':'Fra','Bill to':'Fakturer til','Description':'Beskrivelse','Qty':'Ant.','Rate':'Pris','Subtotal':'Delsum','Tax':'MVA / skatt','Discount':'Rabatt','Total':'Totalt','Notes':'Notater','Remove':'Fjern','Save with SoloBizKit Pro':'Lagre med SoloBizKit Pro','Open SoloBizKit Pro':'Åpne SoloBizKit Pro'
    },
    sv:{
      'Free · private · no account required':'Gratis · privat · inget konto krävs','Free Invoice Generator':'Gratis fakturagenerator','Create a professional invoice with multiple line items, tax, discounts, your logo, payment terms and notes. Your draft auto-saves locally in this browser, then you can print or save the invoice as a PDF.':'Skapa en professionell faktura med flera rader, skatt/moms, rabatt, logotyp, betalningsvillkor och anteckningar. Utkastet sparas lokalt i webbläsaren och kan skrivas ut eller sparas som PDF.','Free to use':'Gratis att använda','No SoloBizKit account':'Inget SoloBizKit-konto','Auto-saves locally':'Sparas lokalt automatiskt','Print or save as PDF':'Skriv ut eller spara som PDF','New invoice':'Ny faktura','Duplicate':'Duplicera','Saved locally':'Sparad lokalt','Print / Save PDF':'Skriv ut / spara PDF','Your business':'Ditt företag','Business name':'Företagsnamn','Logo (optional)':'Logotyp (valfri)','Email':'E-post','Phone':'Telefon','Business address':'Företagsadress','Client & invoice details':'Kund- och fakturauppgifter','Client / company':'Kund / företag','Client email':'Kundens e-post','Client address':'Kundadress','Invoice #':'Fakturanr.','Issue date':'Fakturadatum','Due date':'Förfallodatum','Currency':'Valuta','Payment terms':'Betalningsvillkor','Due on receipt':'Förfaller vid mottagande','Line items':'Fakturarader','+ Add line item':'+ Lägg till rad','Totals & notes':'Summor och anteckningar','Tax %':'Moms / skatt %','Discount %':'Rabatt %','Notes / payment instructions':'Anteckningar / betalningsinstruktioner','Invoice':'Faktura','From':'Från','Bill to':'Fakturera till','Description':'Beskrivning','Qty':'Antal','Rate':'Pris','Subtotal':'Delsumma','Tax':'Moms / skatt','Discount':'Rabatt','Total':'Totalt','Notes':'Anteckningar','Remove':'Ta bort','Save with SoloBizKit Pro':'Spara med SoloBizKit Pro','Open SoloBizKit Pro':'Öppna SoloBizKit Pro'
    },
    de:{
      'Free · private · no account required':'Kostenlos · privat · kein Konto erforderlich','Free Invoice Generator':'Kostenloser Rechnungsgenerator','Create a professional invoice with multiple line items, tax, discounts, your logo, payment terms and notes. Your draft auto-saves locally in this browser, then you can print or save the invoice as a PDF.':'Erstelle eine professionelle Rechnung mit mehreren Positionen, Steuer, Rabatten, Logo, Zahlungsbedingungen und Notizen. Der Entwurf wird lokal im Browser gespeichert und kann gedruckt oder als PDF gespeichert werden.','Free to use':'Kostenlos','No SoloBizKit account':'Kein SoloBizKit-Konto','Auto-saves locally':'Automatisch lokal gespeichert','Print or save as PDF':'Drucken oder als PDF speichern','New invoice':'Neue Rechnung','Duplicate':'Duplizieren','Saved locally':'Lokal gespeichert','Print / Save PDF':'Drucken / PDF speichern','Your business':'Dein Unternehmen','Business name':'Unternehmensname','Logo (optional)':'Logo (optional)','Email':'E-Mail','Phone':'Telefon','Business address':'Geschäftsadresse','Client & invoice details':'Kunden- und Rechnungsdaten','Client / company':'Kunde / Unternehmen','Client email':'E-Mail des Kunden','Client address':'Kundenadresse','Invoice #':'Rechnungsnr.','Issue date':'Rechnungsdatum','Due date':'Fälligkeitsdatum','Currency':'Währung','Payment terms':'Zahlungsbedingungen','Due on receipt':'Sofort fällig','Line items':'Positionen','+ Add line item':'+ Position hinzufügen','Totals & notes':'Summen und Notizen','Tax %':'Steuer %','Discount %':'Rabatt %','Notes / payment instructions':'Notizen / Zahlungsanweisungen','Invoice':'Rechnung','From':'Von','Bill to':'Rechnung an','Description':'Beschreibung','Qty':'Menge','Rate':'Preis','Subtotal':'Zwischensumme','Tax':'Steuer','Discount':'Rabatt','Total':'Gesamt','Notes':'Notizen','Remove':'Entfernen','Save with SoloBizKit Pro':'Mit SoloBizKit Pro speichern','Open SoloBizKit Pro':'SoloBizKit Pro öffnen'
    },
    es:{
      'Free · private · no account required':'Gratis · privado · sin cuenta','Free Invoice Generator':'Generador de facturas gratis','Create a professional invoice with multiple line items, tax, discounts, your logo, payment terms and notes. Your draft auto-saves locally in this browser, then you can print or save the invoice as a PDF.':'Crea una factura profesional con varias líneas, impuestos, descuentos, logotipo, condiciones de pago y notas. El borrador se guarda localmente en el navegador y puedes imprimirlo o guardarlo como PDF.','Free to use':'Gratis','No SoloBizKit account':'Sin cuenta SoloBizKit','Auto-saves locally':'Guardado local automático','Print or save as PDF':'Imprimir o guardar como PDF','New invoice':'Nueva factura','Duplicate':'Duplicar','Saved locally':'Guardado localmente','Print / Save PDF':'Imprimir / guardar PDF','Your business':'Tu negocio','Business name':'Nombre del negocio','Logo (optional)':'Logotipo (opcional)','Email':'Correo electrónico','Phone':'Teléfono','Business address':'Dirección del negocio','Client & invoice details':'Datos del cliente y factura','Client / company':'Cliente / empresa','Client email':'Correo del cliente','Client address':'Dirección del cliente','Invoice #':'N.º de factura','Issue date':'Fecha de emisión','Due date':'Fecha de vencimiento','Currency':'Moneda','Payment terms':'Condiciones de pago','Due on receipt':'Pago al recibir','Line items':'Líneas de factura','+ Add line item':'+ Añadir línea','Totals & notes':'Totales y notas','Tax %':'Impuesto %','Discount %':'Descuento %','Notes / payment instructions':'Notas / instrucciones de pago','Invoice':'Factura','From':'De','Bill to':'Facturar a','Description':'Descripción','Qty':'Cant.','Rate':'Precio','Subtotal':'Subtotal','Tax':'Impuesto','Discount':'Descuento','Total':'Total','Notes':'Notas','Remove':'Eliminar','Save with SoloBizKit Pro':'Guardar con SoloBizKit Pro','Open SoloBizKit Pro':'Abrir SoloBizKit Pro'
    },
    fr:{
      'Free · private · no account required':'Gratuit · privé · sans compte','Free Invoice Generator':'Générateur de factures gratuit','Create a professional invoice with multiple line items, tax, discounts, your logo, payment terms and notes. Your draft auto-saves locally in this browser, then you can print or save the invoice as a PDF.':'Créez une facture professionnelle avec plusieurs lignes, taxes, remises, logo, conditions de paiement et notes. Le brouillon est enregistré localement dans le navigateur puis peut être imprimé ou sauvegardé en PDF.','Free to use':'Gratuit','No SoloBizKit account':'Sans compte SoloBizKit','Auto-saves locally':'Enregistrement local automatique','Print or save as PDF':'Imprimer ou enregistrer en PDF','New invoice':'Nouvelle facture','Duplicate':'Dupliquer','Saved locally':'Enregistré localement','Print / Save PDF':'Imprimer / enregistrer PDF','Your business':'Votre entreprise','Business name':'Nom de l’entreprise','Logo (optional)':'Logo (facultatif)','Email':'E-mail','Phone':'Téléphone','Business address':'Adresse de l’entreprise','Client & invoice details':'Client et détails de facture','Client / company':'Client / entreprise','Client email':'E-mail du client','Client address':'Adresse du client','Invoice #':'N° de facture','Issue date':'Date d’émission','Due date':'Date d’échéance','Currency':'Devise','Payment terms':'Conditions de paiement','Due on receipt':'À réception','Line items':'Lignes de facture','+ Add line item':'+ Ajouter une ligne','Totals & notes':'Totaux et notes','Tax %':'Taxe %','Discount %':'Remise %','Notes / payment instructions':'Notes / instructions de paiement','Invoice':'Facture','From':'De','Bill to':'Facturer à','Description':'Description','Qty':'Qté','Rate':'Prix','Subtotal':'Sous-total','Tax':'Taxe','Discount':'Remise','Total':'Total','Notes':'Notes','Remove':'Supprimer','Save with SoloBizKit Pro':'Enregistrer avec SoloBizKit Pro','Open SoloBizKit Pro':'Ouvrir SoloBizKit Pro'
    }
  };
  const source=new WeakMap();let busy=false;
  function translate(root=document.body){if(busy||!root)return;busy=true;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode())){const p=n.parentElement;if(!p||['SCRIPT','STYLE','TEXTAREA','OPTION'].includes(p.tagName))continue;if(!source.has(n))source.set(n,n.nodeValue||'');const raw=source.get(n)||'',key=raw.trim(),value=D[lang]?.[key];if(value)n.nodeValue=raw.replace(key,value)}busy=false}
  function run(){translate();const observer=new MutationObserver(()=>{if(!busy)requestAnimationFrame(()=>translate())});observer.observe(document.body,{childList:true,subtree:true});document.documentElement.lang=lang}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();