(function(){
  'use strict';
  if(location.pathname.startsWith('/pro/')||location.pathname.startsWith('/lead/'))return;

  const STORAGE_KEY='sbk_language';
  const supported=['en','no','sv','de','es','fr'];
  const htmlLang={en:'en',no:'no',sv:'sv',de:'de',es:'es',fr:'fr'};
  const dictionaries={
    no:{
      'Calculators':'Kalkulatorer','Invoices':'Fakturaer','PDF Tools':'PDF-verktøy','QR Codes':'QR-koder','Guides':'Guider','About':'Om','All Tools':'Alle verktøy','Tools':'Verktøy','Pricing':'Priser','Privacy':'Personvern','Contact':'Kontakt','Terms':'Vilkår','Security':'Sikkerhet','Language':'Språk',
      'Business Calculators':'Bedriftskalkulatorer','Invoice Generator':'Fakturagenerator','24 Free PDF Tools':'24 gratis PDF-verktøy','QR Code Generator':'QR-kodegenerator','Profit Margin Calculator':'Fortjenestemargin-kalkulator','Break-Even Calculator':'Nullpunkt-kalkulator','ROI Calculator':'ROI-kalkulator','Business Loan Calculator':'Bedriftslån-kalkulator','Cash Flow Calculator':'Kontantstrøm-kalkulator','Hourly Rate Calculator':'Timepris-kalkulator','Invoice Number Generator':'Fakturanummer-generator','Compress PDF':'Komprimer PDF','Merge PDF':'Slå sammen PDF','PDF to Word':'PDF til Word','Wi-Fi QR Code':'Wi-Fi QR-kode','Business Name Generator':'Firmanavn-generator','Sign PDF':'Signer PDF','Protect PDF':'Beskytt PDF','Unlock PDF':'Lås opp PDF','Crop PDF':'Beskjær PDF','Reorder PDF Pages':'Endre rekkefølge på PDF-sider','Extract PDF Pages':'Trekk ut PDF-sider','PDF to Excel':'PDF til Excel','PDF to Text':'PDF til tekst','PDF to HTML':'PDF til HTML','HTML to PDF':'HTML til PDF','PDF to JPG':'PDF til JPG','PDF to PNG':'PDF til PNG','JPG to PDF':'JPG til PDF','PNG to PDF':'PNG til PDF','Word to PDF':'Word til PDF','Edit PDF':'Rediger PDF','Split PDF':'Del PDF','Rotate PDF':'Roter PDF','Delete PDF Pages':'Slett PDF-sider','Number PDF Pages':'Nummerer PDF-sider','Watermark PDF':'Vannmerk PDF',
      'Calculate':'Beregn','Calculate →':'Beregn →','Generate':'Generer','Generate →':'Generer →','Create':'Opprett','Create →':'Opprett →','Convert':'Konverter','Convert →':'Konverter →','Download':'Last ned','Download →':'Last ned →','Upload':'Last opp','Choose file':'Velg fil','Choose files':'Velg filer','Select file':'Velg fil','Select files':'Velg filer','Remove':'Fjern','Clear':'Tøm','Copy':'Kopier','Open PDF tools →':'Åpne PDF-verktøy →','Create an invoice →':'Opprett faktura →','Create a QR code →':'Lag QR-kode →','Choose a calculator →':'Velg kalkulator →','Browse every free tool':'Se alle gratisverktøy','Open business calculators':'Åpne bedriftskalkulatorer',
      'Your numbers':'Dine tall','Results':'Resultater','Result':'Resultat','Reset':'Nullstill','Currency':'Valuta','Amount':'Beløp','Revenue':'Omsetning','Cost':'Kostnad','Costs':'Kostnader','Profit':'Fortjeneste','Margin':'Margin','Markup':'Påslag','Price':'Pris','Monthly payment':'Månedlig betaling','Interest':'Renter','Total interest':'Totale renter','Fixed costs':'Faste kostnader','Variable cost':'Variabel kostnad','Hourly rate':'Timepris','Hours':'Timer','Days':'Dager','Months':'Måneder','Years':'År','File':'Fil','Files':'Filer','Page':'Side','Pages':'Sider','Quality':'Kvalitet','Width':'Bredde','Height':'Høyde','Password':'Passord','Text':'Tekst','Color':'Farge','Size':'Størrelse',
      'Free small-business tools · no signup required':'Gratis småbedriftsverktøy · ingen registrering nødvendig','Calculate, invoice and finish business work in one place.':'Beregn, fakturer og få bedriftsarbeidet ferdig på ett sted.','Use clear business calculators, create client invoices, prepare PDF documents and generate QR codes without switching between a dozen sites.':'Bruk tydelige bedriftskalkulatorer, lag kundefakturaer, klargjør PDF-dokumenter og generer QR-koder uten å hoppe mellom mange nettsteder.','Start with a complete toolkit':'Start med et komplett verktøysett','Choose a category or search for the exact job you need to finish.':'Velg en kategori eller søk etter oppgaven du vil få gjort.','Popular tools by business task':'Populære verktøy etter bedriftsoppgave','Need to manage the work too?':'Trenger du også å administrere arbeidet?','Explore SoloBizKit Pro':'Utforsk SoloBizKit Pro','Open Pro':'Åpne Pro','Simple CRM':'Enkel CRM','Estimates to invoices':'Tilbud til faktura','Recurring billing & payments':'Gjentakende fakturering og betalinger','Search free SoloBizKit tools':'Søk i gratis SoloBizKit-verktøy','Search tools':'Søk i verktøy','No exact match.':'Ingen treff.','Try a shorter search, or':'Prøv et kortere søk, eller','browse all tools':'se alle verktøy'
    },
    sv:{
      'Calculators':'Kalkylatorer','Invoices':'Fakturor','PDF Tools':'PDF-verktyg','QR Codes':'QR-koder','Guides':'Guider','About':'Om','All Tools':'Alla verktyg','Tools':'Verktyg','Pricing':'Priser','Privacy':'Integritet','Contact':'Kontakt','Terms':'Villkor','Security':'Säkerhet','Language':'Språk',
      'Business Calculators':'Företagskalkylatorer','Invoice Generator':'Fakturagenerator','24 Free PDF Tools':'24 gratis PDF-verktyg','QR Code Generator':'QR-kodgenerator','Profit Margin Calculator':'Vinstmarginalkalkylator','Break-Even Calculator':'Nollpunktskalkylator','ROI Calculator':'ROI-kalkylator','Business Loan Calculator':'Företagslånekalkylator','Cash Flow Calculator':'Kassaflödeskalkylator','Hourly Rate Calculator':'Timpriskalkylator','Invoice Number Generator':'Fakturanummergenerator','Compress PDF':'Komprimera PDF','Merge PDF':'Slå ihop PDF','PDF to Word':'PDF till Word','Wi-Fi QR Code':'Wi-Fi QR-kod','Business Name Generator':'Företagsnamnsgenerator','Sign PDF':'Signera PDF','Protect PDF':'Skydda PDF','Unlock PDF':'Lås upp PDF','Crop PDF':'Beskär PDF','Reorder PDF Pages':'Ändra ordning på PDF-sidor','Extract PDF Pages':'Extrahera PDF-sidor','PDF to Excel':'PDF till Excel','PDF to Text':'PDF till text','PDF to HTML':'PDF till HTML','HTML to PDF':'HTML till PDF','PDF to JPG':'PDF till JPG','PDF to PNG':'PDF till PNG','JPG to PDF':'JPG till PDF','PNG to PDF':'PNG till PDF','Word to PDF':'Word till PDF','Edit PDF':'Redigera PDF','Split PDF':'Dela PDF','Rotate PDF':'Rotera PDF','Delete PDF Pages':'Ta bort PDF-sidor','Number PDF Pages':'Numrera PDF-sidor','Watermark PDF':'Vattenmärk PDF',
      'Calculate':'Beräkna','Calculate →':'Beräkna →','Generate':'Generera','Generate →':'Generera →','Create':'Skapa','Create →':'Skapa →','Convert':'Konvertera','Convert →':'Konvertera →','Download':'Ladda ner','Download →':'Ladda ner →','Upload':'Ladda upp','Choose file':'Välj fil','Choose files':'Välj filer','Select file':'Välj fil','Select files':'Välj filer','Remove':'Ta bort','Clear':'Rensa','Copy':'Kopiera','Open PDF tools →':'Öppna PDF-verktyg →','Create an invoice →':'Skapa faktura →','Create a QR code →':'Skapa QR-kod →','Choose a calculator →':'Välj kalkylator →','Browse every free tool':'Se alla gratisverktyg','Open business calculators':'Öppna företagskalkylatorer','Your numbers':'Dina siffror','Results':'Resultat','Result':'Resultat','Reset':'Återställ','Currency':'Valuta','Amount':'Belopp','Revenue':'Intäkter','Cost':'Kostnad','Costs':'Kostnader','Profit':'Vinst','Margin':'Marginal','Markup':'Påslag','Price':'Pris','Monthly payment':'Månadsbetalning','Interest':'Ränta','Total interest':'Total ränta','Fixed costs':'Fasta kostnader','Variable cost':'Rörlig kostnad','Hourly rate':'Timpris','Hours':'Timmar','Days':'Dagar','Months':'Månader','Years':'År','File':'Fil','Files':'Filer','Page':'Sida','Pages':'Sidor','Quality':'Kvalitet','Width':'Bredd','Height':'Höjd','Password':'Lösenord','Text':'Text','Color':'Färg','Size':'Storlek',
      'Free small-business tools · no signup required':'Gratis småföretagsverktyg · ingen registrering krävs','Calculate, invoice and finish business work in one place.':'Räkna, fakturera och få företagsarbetet klart på ett ställe.','Use clear business calculators, create client invoices, prepare PDF documents and generate QR codes without switching between a dozen sites.':'Använd tydliga företagskalkylatorer, skapa kundfakturor, förbered PDF-dokument och generera QR-koder utan att byta mellan många webbplatser.','Start with a complete toolkit':'Börja med ett komplett verktygspaket','Choose a category or search for the exact job you need to finish.':'Välj en kategori eller sök efter uppgiften du vill slutföra.','Popular tools by business task':'Populära verktyg efter företagsuppgift','Need to manage the work too?':'Behöver du även hantera arbetet?','Explore SoloBizKit Pro':'Utforska SoloBizKit Pro','Open Pro':'Öppna Pro','Simple CRM':'Enkel CRM','Estimates to invoices':'Offerter till fakturor','Recurring billing & payments':'Återkommande fakturering och betalningar','Search free SoloBizKit tools':'Sök bland gratis SoloBizKit-verktyg','Search tools':'Sök verktyg','No exact match.':'Ingen exakt träff.','Try a shorter search, or':'Prova en kortare sökning, eller','browse all tools':'se alla verktyg'
    },
    de:{
      'Calculators':'Rechner','Invoices':'Rechnungen','PDF Tools':'PDF-Tools','QR Codes':'QR-Codes','Guides':'Ratgeber','About':'Über uns','All Tools':'Alle Tools','Tools':'Tools','Pricing':'Preise','Privacy':'Datenschutz','Contact':'Kontakt','Terms':'Bedingungen','Security':'Sicherheit','Language':'Sprache',
      'Business Calculators':'Business-Rechner','Invoice Generator':'Rechnungsgenerator','24 Free PDF Tools':'24 kostenlose PDF-Tools','QR Code Generator':'QR-Code-Generator','Profit Margin Calculator':'Gewinnmargen-Rechner','Break-Even Calculator':'Break-even-Rechner','ROI Calculator':'ROI-Rechner','Business Loan Calculator':'Geschäftskredit-Rechner','Cash Flow Calculator':'Cashflow-Rechner','Hourly Rate Calculator':'Stundensatz-Rechner','Invoice Number Generator':'Rechnungsnummer-Generator','Compress PDF':'PDF komprimieren','Merge PDF':'PDF zusammenfügen','PDF to Word':'PDF zu Word','Wi-Fi QR Code':'WLAN-QR-Code','Business Name Generator':'Firmennamen-Generator','Sign PDF':'PDF signieren','Protect PDF':'PDF schützen','Unlock PDF':'PDF entsperren','Crop PDF':'PDF zuschneiden','Reorder PDF Pages':'PDF-Seiten neu anordnen','Extract PDF Pages':'PDF-Seiten extrahieren','PDF to Excel':'PDF zu Excel','PDF to Text':'PDF zu Text','PDF to HTML':'PDF zu HTML','HTML to PDF':'HTML zu PDF','PDF to JPG':'PDF zu JPG','PDF to PNG':'PDF zu PNG','JPG to PDF':'JPG zu PDF','PNG to PDF':'PNG zu PDF','Word to PDF':'Word zu PDF','Edit PDF':'PDF bearbeiten','Split PDF':'PDF teilen','Rotate PDF':'PDF drehen','Delete PDF Pages':'PDF-Seiten löschen','Number PDF Pages':'PDF-Seiten nummerieren','Watermark PDF':'PDF mit Wasserzeichen',
      'Calculate':'Berechnen','Calculate →':'Berechnen →','Generate':'Generieren','Generate →':'Generieren →','Create':'Erstellen','Create →':'Erstellen →','Convert':'Konvertieren','Convert →':'Konvertieren →','Download':'Herunterladen','Download →':'Herunterladen →','Upload':'Hochladen','Choose file':'Datei auswählen','Choose files':'Dateien auswählen','Select file':'Datei auswählen','Select files':'Dateien auswählen','Remove':'Entfernen','Clear':'Leeren','Copy':'Kopieren','Open PDF tools →':'PDF-Tools öffnen →','Create an invoice →':'Rechnung erstellen →','Create a QR code →':'QR-Code erstellen →','Choose a calculator →':'Rechner auswählen →','Browse every free tool':'Alle kostenlosen Tools ansehen','Open business calculators':'Business-Rechner öffnen','Your numbers':'Deine Zahlen','Results':'Ergebnisse','Result':'Ergebnis','Reset':'Zurücksetzen','Currency':'Währung','Amount':'Betrag','Revenue':'Umsatz','Cost':'Kosten','Costs':'Kosten','Profit':'Gewinn','Margin':'Marge','Markup':'Aufschlag','Price':'Preis','Monthly payment':'Monatsrate','Interest':'Zinsen','Total interest':'Gesamtzinsen','Fixed costs':'Fixkosten','Variable cost':'Variable Kosten','Hourly rate':'Stundensatz','Hours':'Stunden','Days':'Tage','Months':'Monate','Years':'Jahre','File':'Datei','Files':'Dateien','Page':'Seite','Pages':'Seiten','Quality':'Qualität','Width':'Breite','Height':'Höhe','Password':'Passwort','Text':'Text','Color':'Farbe','Size':'Größe',
      'Free small-business tools · no signup required':'Kostenlose Tools für kleine Unternehmen · keine Anmeldung erforderlich','Calculate, invoice and finish business work in one place.':'Rechnen, fakturieren und Geschäftsaufgaben an einem Ort erledigen.','Use clear business calculators, create client invoices, prepare PDF documents and generate QR codes without switching between a dozen sites.':'Nutze verständliche Business-Rechner, erstelle Kundenrechnungen, bearbeite PDF-Dokumente und generiere QR-Codes ohne ständig die Website zu wechseln.','Start with a complete toolkit':'Starte mit einem kompletten Toolkit','Choose a category or search for the exact job you need to finish.':'Wähle eine Kategorie oder suche nach der Aufgabe, die du erledigen möchtest.','Popular tools by business task':'Beliebte Tools nach Geschäftsaufgabe','Need to manage the work too?':'Musst du auch die Arbeit verwalten?','Explore SoloBizKit Pro':'SoloBizKit Pro entdecken','Open Pro':'Pro öffnen','Simple CRM':'Einfaches CRM','Estimates to invoices':'Angebote zu Rechnungen','Recurring billing & payments':'Wiederkehrende Rechnungen & Zahlungen','Search free SoloBizKit tools':'Kostenlose SoloBizKit-Tools durchsuchen','Search tools':'Tools durchsuchen','No exact match.':'Kein exakter Treffer.','Try a shorter search, or':'Versuche eine kürzere Suche oder','browse all tools':'alle Tools ansehen'
    },
    es:{
      'Calculators':'Calculadoras','Invoices':'Facturas','PDF Tools':'Herramientas PDF','QR Codes':'Códigos QR','Guides':'Guías','About':'Acerca de','All Tools':'Todas las herramientas','Tools':'Herramientas','Pricing':'Precios','Privacy':'Privacidad','Contact':'Contacto','Terms':'Términos','Security':'Seguridad','Language':'Idioma',
      'Business Calculators':'Calculadoras de negocio','Invoice Generator':'Generador de facturas','24 Free PDF Tools':'24 herramientas PDF gratis','QR Code Generator':'Generador de códigos QR','Profit Margin Calculator':'Calculadora de margen de beneficio','Break-Even Calculator':'Calculadora de punto de equilibrio','ROI Calculator':'Calculadora ROI','Business Loan Calculator':'Calculadora de préstamo empresarial','Cash Flow Calculator':'Calculadora de flujo de caja','Hourly Rate Calculator':'Calculadora de tarifa por hora','Invoice Number Generator':'Generador de número de factura','Compress PDF':'Comprimir PDF','Merge PDF':'Unir PDF','PDF to Word':'PDF a Word','Wi-Fi QR Code':'Código QR Wi-Fi','Business Name Generator':'Generador de nombres de empresa','Sign PDF':'Firmar PDF','Protect PDF':'Proteger PDF','Unlock PDF':'Desbloquear PDF','Crop PDF':'Recortar PDF','Reorder PDF Pages':'Reordenar páginas PDF','Extract PDF Pages':'Extraer páginas PDF','PDF to Excel':'PDF a Excel','PDF to Text':'PDF a texto','PDF to HTML':'PDF a HTML','HTML to PDF':'HTML a PDF','PDF to JPG':'PDF a JPG','PDF to PNG':'PDF a PNG','JPG to PDF':'JPG a PDF','PNG to PDF':'PNG a PDF','Word to PDF':'Word a PDF','Edit PDF':'Editar PDF','Split PDF':'Dividir PDF','Rotate PDF':'Girar PDF','Delete PDF Pages':'Eliminar páginas PDF','Number PDF Pages':'Numerar páginas PDF','Watermark PDF':'Marca de agua PDF',
      'Calculate':'Calcular','Calculate →':'Calcular →','Generate':'Generar','Generate →':'Generar →','Create':'Crear','Create →':'Crear →','Convert':'Convertir','Convert →':'Convertir →','Download':'Descargar','Download →':'Descargar →','Upload':'Subir','Choose file':'Elegir archivo','Choose files':'Elegir archivos','Select file':'Seleccionar archivo','Select files':'Seleccionar archivos','Remove':'Eliminar','Clear':'Limpiar','Copy':'Copiar','Open PDF tools →':'Abrir herramientas PDF →','Create an invoice →':'Crear factura →','Create a QR code →':'Crear código QR →','Choose a calculator →':'Elegir calculadora →','Browse every free tool':'Ver todas las herramientas gratis','Open business calculators':'Abrir calculadoras de negocio','Your numbers':'Tus cifras','Results':'Resultados','Result':'Resultado','Reset':'Restablecer','Currency':'Moneda','Amount':'Importe','Revenue':'Ingresos','Cost':'Coste','Costs':'Costes','Profit':'Beneficio','Margin':'Margen','Markup':'Margen sobre coste','Price':'Precio','Monthly payment':'Pago mensual','Interest':'Intereses','Total interest':'Intereses totales','Fixed costs':'Costes fijos','Variable cost':'Coste variable','Hourly rate':'Tarifa por hora','Hours':'Horas','Days':'Días','Months':'Meses','Years':'Años','File':'Archivo','Files':'Archivos','Page':'Página','Pages':'Páginas','Quality':'Calidad','Width':'Ancho','Height':'Alto','Password':'Contraseña','Text':'Texto','Color':'Color','Size':'Tamaño',
      'Free small-business tools · no signup required':'Herramientas gratis para pequeños negocios · sin registro','Calculate, invoice and finish business work in one place.':'Calcula, factura y termina tareas de negocio en un solo lugar.','Use clear business calculators, create client invoices, prepare PDF documents and generate QR codes without switching between a dozen sites.':'Usa calculadoras claras, crea facturas, prepara documentos PDF y genera códigos QR sin cambiar entre muchas webs.','Start with a complete toolkit':'Empieza con un kit completo','Choose a category or search for the exact job you need to finish.':'Elige una categoría o busca la tarea que quieres completar.','Popular tools by business task':'Herramientas populares por tarea','Need to manage the work too?':'¿También necesitas gestionar el trabajo?','Explore SoloBizKit Pro':'Explorar SoloBizKit Pro','Open Pro':'Abrir Pro','Simple CRM':'CRM sencillo','Estimates to invoices':'Presupuestos a facturas','Recurring billing & payments':'Facturación recurrente y pagos','Search free SoloBizKit tools':'Buscar herramientas gratis de SoloBizKit','Search tools':'Buscar herramientas','No exact match.':'Sin coincidencia exacta.','Try a shorter search, or':'Prueba una búsqueda más corta o','browse all tools':'ver todas las herramientas'
    },
    fr:{
      'Calculators':'Calculateurs','Invoices':'Factures','PDF Tools':'Outils PDF','QR Codes':'Codes QR','Guides':'Guides','About':'À propos','All Tools':'Tous les outils','Tools':'Outils','Pricing':'Tarifs','Privacy':'Confidentialité','Contact':'Contact','Terms':'Conditions','Security':'Sécurité','Language':'Langue',
      'Business Calculators':'Calculateurs professionnels','Invoice Generator':'Générateur de factures','24 Free PDF Tools':'24 outils PDF gratuits','QR Code Generator':'Générateur de codes QR','Profit Margin Calculator':'Calculateur de marge bénéficiaire','Break-Even Calculator':'Calculateur de seuil de rentabilité','ROI Calculator':'Calculateur ROI','Business Loan Calculator':'Calculateur de prêt professionnel','Cash Flow Calculator':'Calculateur de trésorerie','Hourly Rate Calculator':'Calculateur de taux horaire','Invoice Number Generator':'Générateur de numéro de facture','Compress PDF':'Compresser PDF','Merge PDF':'Fusionner PDF','PDF to Word':'PDF vers Word','Wi-Fi QR Code':'Code QR Wi-Fi','Business Name Generator':'Générateur de nom d’entreprise','Sign PDF':'Signer PDF','Protect PDF':'Protéger PDF','Unlock PDF':'Déverrouiller PDF','Crop PDF':'Rogner PDF','Reorder PDF Pages':'Réorganiser les pages PDF','Extract PDF Pages':'Extraire les pages PDF','PDF to Excel':'PDF vers Excel','PDF to Text':'PDF vers texte','PDF to HTML':'PDF vers HTML','HTML to PDF':'HTML vers PDF','PDF to JPG':'PDF vers JPG','PDF to PNG':'PDF vers PNG','JPG to PDF':'JPG vers PDF','PNG to PDF':'PNG vers PDF','Word to PDF':'Word vers PDF','Edit PDF':'Modifier PDF','Split PDF':'Diviser PDF','Rotate PDF':'Faire pivoter PDF','Delete PDF Pages':'Supprimer des pages PDF','Number PDF Pages':'Numéroter les pages PDF','Watermark PDF':'Filigraner PDF',
      'Calculate':'Calculer','Calculate →':'Calculer →','Generate':'Générer','Generate →':'Générer →','Create':'Créer','Create →':'Créer →','Convert':'Convertir','Convert →':'Convertir →','Download':'Télécharger','Download →':'Télécharger →','Upload':'Téléverser','Choose file':'Choisir un fichier','Choose files':'Choisir des fichiers','Select file':'Sélectionner un fichier','Select files':'Sélectionner des fichiers','Remove':'Supprimer','Clear':'Effacer','Copy':'Copier','Open PDF tools →':'Ouvrir les outils PDF →','Create an invoice →':'Créer une facture →','Create a QR code →':'Créer un code QR →','Choose a calculator →':'Choisir un calculateur →','Browse every free tool':'Voir tous les outils gratuits','Open business calculators':'Ouvrir les calculateurs professionnels','Your numbers':'Vos chiffres','Results':'Résultats','Result':'Résultat','Reset':'Réinitialiser','Currency':'Devise','Amount':'Montant','Revenue':'Chiffre d’affaires','Cost':'Coût','Costs':'Coûts','Profit':'Bénéfice','Margin':'Marge','Markup':'Majoration','Price':'Prix','Monthly payment':'Mensualité','Interest':'Intérêts','Total interest':'Intérêts totaux','Fixed costs':'Coûts fixes','Variable cost':'Coût variable','Hourly rate':'Taux horaire','Hours':'Heures','Days':'Jours','Months':'Mois','Years':'Années','File':'Fichier','Files':'Fichiers','Page':'Page','Pages':'Pages','Quality':'Qualité','Width':'Largeur','Height':'Hauteur','Password':'Mot de passe','Text':'Texte','Color':'Couleur','Size':'Taille',
      'Free small-business tools · no signup required':'Outils gratuits pour petites entreprises · sans inscription','Calculate, invoice and finish business work in one place.':'Calculez, facturez et terminez vos tâches professionnelles au même endroit.','Use clear business calculators, create client invoices, prepare PDF documents and generate QR codes without switching between a dozen sites.':'Utilisez des calculateurs clairs, créez des factures, préparez des PDF et générez des codes QR sans passer d’un site à l’autre.','Start with a complete toolkit':'Commencez avec une boîte à outils complète','Choose a category or search for the exact job you need to finish.':'Choisissez une catégorie ou recherchez la tâche à accomplir.','Popular tools by business task':'Outils populaires par tâche','Need to manage the work too?':'Besoin aussi de gérer le travail ?','Explore SoloBizKit Pro':'Découvrir SoloBizKit Pro','Open Pro':'Ouvrir Pro','Simple CRM':'CRM simple','Estimates to invoices':'Devis vers factures','Recurring billing & payments':'Facturation récurrente et paiements','Search free SoloBizKit tools':'Rechercher les outils gratuits SoloBizKit','Search tools':'Rechercher des outils','No exact match.':'Aucun résultat exact.','Try a shorter search, or':'Essayez une recherche plus courte ou','browse all tools':'voir tous les outils'
    }
  };

  const nodeSource=new WeakMap();
  const attrSource=new WeakMap();
  let applying=false;
  function pathLanguage(){const m=location.pathname.match(/^\/(no|sv|de|es|fr)(?:\/|$)/);return m?m[1]:null}
  function savedLanguage(){try{const v=localStorage.getItem(STORAGE_KEY);return supported.includes(v)?v:null}catch(_){return null}}
  function language(){return pathLanguage()||savedLanguage()||'en'}
  function translate(source,lang){return lang==='en'?source:(dictionaries[lang]?.[source]||source)}
  function preserve(raw,value){const a=raw.match(/^\s*/)?.[0]||'';const b=raw.match(/\s*$/)?.[0]||'';return a+value+b}
  function skipText(el){return !el||el.closest?.('.sbk-language-switcher')||['SCRIPT','STYLE','NOSCRIPT'].includes(el.tagName)||el.isContentEditable}
  function skipAttrs(el){return !(el instanceof Element)||el.closest?.('.sbk-language-switcher')||['SCRIPT','STYLE','NOSCRIPT'].includes(el.tagName)}

  function applyText(node,lang){
    const parent=node.parentElement;if(skipText(parent))return;
    if(!nodeSource.has(node))nodeSource.set(node,node.nodeValue||'');
    const raw=nodeSource.get(node)||'';const key=raw.trim();if(!key)return;
    const next=preserve(raw,translate(key,lang));if(node.nodeValue!==next)node.nodeValue=next;
  }
  function applyAttrs(el,lang){
    if(skipAttrs(el))return;
    let source=attrSource.get(el);if(!source){source={};attrSource.set(el,source)}
    for(const attr of ['placeholder','aria-label','title','alt']){
      if(!el.hasAttribute(attr))continue;
      if(!(attr in source))source[attr]=el.getAttribute(attr)||'';
      const raw=source[attr];const next=translate(raw.trim(),lang);
      if(next!==raw.trim())el.setAttribute(attr,preserve(raw,next));else if(lang==='en')el.setAttribute(attr,raw);
    }
    if(el.tagName==='OPTION'){
      if(!('optionText' in source))source.optionText=el.textContent||'';
      if(!el.hasAttribute('value'))el.setAttribute('value',source.optionText);
      const next=translate(source.optionText.trim(),lang);if(next!==source.optionText.trim())el.textContent=next;else if(lang==='en')el.textContent=source.optionText;
    }
  }
  function apply(root=document.body){
    if(!root||applying)return;applying=true;
    const lang=language();document.documentElement.lang=htmlLang[lang]||'en';
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT|NodeFilter.SHOW_ELEMENT);
    if(root.nodeType===Node.TEXT_NODE)applyText(root,lang);else if(root instanceof Element)applyAttrs(root,lang);
    let node;while((node=walker.nextNode())){if(node.nodeType===Node.TEXT_NODE)applyText(node,lang);else applyAttrs(node,lang)}
    applying=false;
  }
  function boot(){
    const lang=language();try{if(pathLanguage())localStorage.setItem(STORAGE_KEY,lang)}catch(_){ }
    apply();
    const observer=new MutationObserver(()=>{if(!applying)requestAnimationFrame(()=>apply())});
    observer.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['placeholder','aria-label','title','alt']});
    window.sbkPublicI18n={language,apply,translate:(text)=>translate(text,language())};
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();