import { getDataOwnerId, getSession, getWorkspaceContext, loadWorkspace, supabase } from '../backend.js';

const app=document.querySelector('#app');
const authActions=document.querySelector('#authActions');
const shell=document.querySelector('#shell');
const modal=document.querySelector('#dealModal');
const form=document.querySelector('#dealForm');
const modalTitle=document.querySelector('#dealModalTitle');
let session=null,context=null,dataOwner=null,workspace=null,deals=[],tasks=[],editing=null;
const stages=[['new','New lead'],['contacted','Contacted'],['estimate','Estimate'],['negotiation','Negotiation'],['won','Won'],['lost','Lost']];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]);
const today=()=>new Date().toISOString().slice(0,10);
function money(v,c='USD'){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(v)||0)}catch{return `${c} ${Number(v||0).toFixed(0)}`}}
function customer(id){return workspace?.customers?.find(c=>c.id===id)||null}
function taskForDeal(id){return tasks.find(t=>t.deal_id===id&&!t.completed_at)||null}
async function load(){session=await getSession();if(!session?.user?.id){renderAuth();return;}context=await getWorkspaceContext(true);dataOwner=await getDataOwnerId();workspace=await loadWorkspace(session.user.id);shell.classList.remove('signed-out');authActions.innerHTML=`<span class="account-chip"><strong>${esc(context?.name||session.user.email||'Account')}</strong><small>${esc(String(context?.role||'PRO').toUpperCase())}</small></span>`;const[d,t]=await Promise.all([supabase.from('crm_deals').select('*').eq('user_id',dataOwner).order('updated_at',{ascending:false}),supabase.from('crm_tasks').select('*').eq('user_id',dataOwner).order('due_date',{ascending:true})]);if(d.error)throw d.error;if(t.error)throw t.error;deals=d.data||[];tasks=t.data||[];render();}
function renderAuth(){app.innerHTML='<div class="auth-stage"><section class="auth-card"><p class="eyebrow">SOLOBIZKIT PRO</p><h2>Sign in from the main Pro workspace.</h2><a class="btn primary" href="/pro/">Open Pro</a></section></div>'}
function render(){const active=deals.filter(d=>!['won','lost'].includes(d.stage));const forecast=active.reduce((s,d)=>s+(Number(d.amount)||0)*(Number(d.probability)||0)/100,0);const won=deals.filter(d=>d.stage==='won');const overdueTasks=tasks.filter(t=>!t.completed_at&&t.due_date<today());app.innerHTML=`<div class="pipeline-summary"><div class="stat"><div class="label">Open deals</div><div class="value">${active.length}</div></div><div class="stat"><div class="label">Pipeline value</div><div class="value compact-value">${esc(sumByCurrency(active))}</div></div><div class="stat"><div class="label">Weighted forecast</div><div class="value compact-value">${esc(money(forecast,active[0]?.currency||'USD'))}</div></div><div class="stat ${overdueTasks.length?'attention':''}"><div class="label">Overdue tasks</div><div class="value">${overdueTasks.length}</div></div></div><section class="card"><div class="pipeline-toolbar"><div class="left"><input id="pipelineSearch" class="input search" type="search" placeholder="Search deals or customers…"><select id="pipelineCurrency" class="select"><option value="">All currencies</option>${[...new Set(deals.map(d=>d.currency).filter(Boolean))].sort().map(c=>`<option>${esc(c)}</option>`).join('')}</select></div>${context?.canWrite?'<button class="btn primary" id="newDeal">+ Deal</button>':''}</div>${context?.canWrite?'':'<div class="pipeline-readonly">Read-only workspace access. You can view the pipeline, but not move or edit deals.</div>'}<div id="pipelineBoard" class="pipeline-board"></div></section>`;bindFilters();renderBoard();document.querySelector('#newDeal')?.addEventListener('click',()=>openDeal());}
function sumByCurrency(items){const m=new Map();for(const d of items)m.set(d.currency||'USD',(m.get(d.currency||'USD')||0)+Number(d.amount||0));return[...m.entries()].map(([c,v])=>money(v,c)).join(' · ')||'—'}
function filtered(){const q=document.querySelector('#pipelineSearch')?.value.trim().toLowerCase()||'';const c=document.querySelector('#pipelineCurrency')?.value||'';return deals.filter(d=>!c||d.currency===c).filter(d=>{const cust=customer(d.customer_id);return `${d.title} ${cust?.name||''} ${cust?.company||''}`.toLowerCase().includes(q)})}
function renderBoard(){const board=document.querySelector('#pipelineBoard');if(!board)return;const items=filtered();board.innerHTML=stages.map(([key,label])=>{const rows=items.filter(d=>d.stage===key);return`<section class="pipeline-column" data-stage="${key}"><div class="pipeline-column-head"><h3>${esc(label)}</h3><span>${rows.length} · ${esc(sumByCurrency(rows))}</span></div><div class="deal-list">${rows.length?rows.map(dealCard).join(''):'<div class="pipeline-empty">No deals</div>'}</div></section>`}).join('');bindBoard();}
function dealCard(d){const c=customer(d.customer_id);const task=taskForDeal(d.id);const overdue=task&&task.due_date<today();return`<article class="deal-card" data-deal-id="${d.id}" draggable="${context?.canWrite?'true':'false'}"><h4>${esc(d.title)}</h4><p>${esc(c?.name||'No customer')}${c?.company?` · ${esc(c.company)}`:''}</p><div class="deal-meta"><span class="deal-value">${esc(money(d.amount,d.currency))}</span><span>${Number(d.probability||0)}%</span></div>${d.next_action?`<div class="deal-action">${esc(d.next_action)}</div>`:''}${task?`<span class="task-due ${overdue?'overdue':''}">${overdue?'Overdue':'Due'} ${esc(task.due_date)}</span>`:''}${context?.canWrite?'<div class="deal-action"><button class="mini-btn" data-edit-deal>Open</button></div>':''}</article>`}
function bindFilters(){document.querySelector('#pipelineSearch')?.addEventListener('input',renderBoard);document.querySelector('#pipelineCurrency')?.addEventListener('change',renderBoard)}
function bindBoard(){document.querySelectorAll('[data-edit-deal]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openDeal(e.currentTarget.closest('[data-deal-id]').dataset.dealId)}));if(!context?.canWrite)return;document.querySelectorAll('.deal-card').forEach(card=>{card.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',card.dataset.dealId))});document.querySelectorAll('.pipeline-column').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drag-over')});col.addEventListener('dragleave',()=>col.classList.remove('drag-over'));col.addEventListener('drop',async e=>{e.preventDefault();col.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain');await moveDeal(id,col.dataset.stage)})})}
async function moveDeal(id,stage){const d=deals.find(x=>x.id===id);if(!d||d.stage===stage)return;const probability={new:10,contacted:30,estimate:60,negotiation:80,won:100,lost:0}[stage];const{error}=await supabase.from('crm_deals').update({stage,probability,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',dataOwner);if(error)return alert(error.message);d.stage=stage;d.probability=probability;renderBoard()}
function openDeal(id=null){if(!context?.canWrite)return;editing=deals.find(d=>d.id===id)||null;modalTitle.textContent=editing?'Edit deal':'New deal';form.innerHTML=`<div class="form-grid"><div class="field full"><label>Deal name</label><input class="input" name="title" required value="${esc(editing?.title||'')}"></div><div class="field"><label>Customer</label><select class="select" name="customer_id"><option value="">No customer</option>${workspace.customers.map(c=>`<option value="${c.id}" ${editing?.customer_id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Stage</label><select class="select" name="stage">${stages.map(([k,l])=>`<option value="${k}" ${editing?.stage===k?'selected':''}>${esc(l)}</option>`).join('')}</select></div><div class="field"><label>Amount</label><input class="input" name="amount" type="number" min="0" step="0.01" value="${Number(editing?.amount||0)}"></div><div class="field"><label>Currency</label><input class="input" name="currency" maxlength="3" value="${esc(editing?.currency||'USD')}"></div><div class="field"><label>Probability %</label><input class="input" name="probability" type="number" min="0" max="100" value="${Number(editing?.probability??10)}"></div><div class="field"><label>Follow-up date</label><input class="input" name="follow_up_date" type="date" value="${esc(editing?.follow_up_date||'')}"></div><div class="field full"><label>Next action</label><input class="input" name="next_action" value="${esc(editing?.next_action||'')}"></div><div class="field full"><label>Source</label><input class="input" name="source" value="${esc(editing?.source||'')}"></div></div><div class="modal-actions"><button class="btn secondary" value="cancel">Cancel</button><button class="btn primary" value="default">Save deal</button></div>`;modal.showModal()}
form.addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();if(!context?.canWrite)return;const fd=new FormData(form);const stage=String(fd.get('stage')||'new');const payload={user_id:dataOwner,customer_id:String(fd.get('customer_id')||'')||null,title:String(fd.get('title')||'').trim(),stage,amount:Number(fd.get('amount')||0),currency:String(fd.get('currency')||'USD').trim().toUpperCase(),probability:Number(fd.get('probability')||0),follow_up_date:String(fd.get('follow_up_date')||'')||null,next_action:String(fd.get('next_action')||'').trim()||null,source:String(fd.get('source')||'').trim()||null,updated_at:new Date().toISOString()};let r;if(editing)r=await supabase.from('crm_deals').update(payload).eq('id',editing.id).eq('user_id',dataOwner).select().single();else r=await supabase.from('crm_deals').insert(payload).select().single();if(r.error)return alert(r.error.message);if(payload.follow_up_date){await supabase.from('crm_tasks').insert({user_id:dataOwner,customer_id:payload.customer_id,deal_id:r.data.id,title:payload.next_action||`Follow up on ${payload.title}`,due_date:payload.follow_up_date,priority:'normal',task_type:'follow_up',created_by:session.user.id})}modal.close();editing=null;await load()});
load().catch(err=>{console.error(err);app.innerHTML=`<div class="empty">Could not load pipeline: ${esc(err.message||'Unknown error')}</div>`});