import { commitSpreadsheetImport, downloadSpreadsheetTemplate, exportWorkspaceExcel, previewSpreadsheetImport } from './spreadsheet-transfer-workspace.js';

const lang=(()=>{try{return localStorage.getItem('sbk_language')||'en'}catch{return'en'}})();
const C={
 en:['Import Excel','Export Excel','Import contacts','Import catalog','Export all to Excel','Contacts template','Catalog template','DATA IMPORT & EXPORT','Move your business data in or out','Import customers, leads or catalog items from Excel. Export one workbook with customers, leads, invoices, estimates, recurring work and catalog.','Accepts .xlsx, .xls and .csv. Existing matches are skipped instead of overwritten.','Reading spreadsheet…','Preparing Excel…','Preparing template…'],
 no:['Importer Excel','Eksporter Excel','Importer kontakter','Importer katalog','Eksporter alt til Excel','Kontaktmal','Katalogmal','DATAIMPORT OG -EKSPORT','Flytt bedriftsdata inn eller ut','Importer kunder, leads eller katalogelementer fra Excel. Eksporter én arbeidsbok med kunder, leads, fakturaer, tilbud, gjentakende arbeid og katalog.','Støtter .xlsx, .xls og .csv. Eksisterende treff hoppes over og overskrives ikke.','Leser regnearket…','Klargjør Excel…','Klargjør mal…'],
 sv:['Importera Excel','Exportera Excel','Importera kontakter','Importera katalog','Exportera allt till Excel','Kontaktmall','Katalogmall','DATAIMPORT OCH EXPORT','Flytta företagsdata in eller ut','Importera kunder, leads eller katalogposter från Excel. Exportera en arbetsbok med kunder, leads, fakturor, offerter, återkommande arbete och katalog.','Stöder .xlsx, .xls och .csv. Befintliga träffar hoppas över och skrivs inte över.','Läser kalkylbladet…','Förbereder Excel…','Förbereder mall…'],
 de:['Excel importieren','Excel exportieren','Kontakte importieren','Katalog importieren','Alles nach Excel exportieren','Kontaktvorlage','Katalogvorlage','DATENIMPORT & EXPORT','Geschäftsdaten importieren oder exportieren','Importiere Kunden, Leads oder Katalogeinträge aus Excel. Exportiere eine Arbeitsmappe mit Kunden, Leads, Rechnungen, Angeboten, wiederkehrenden Vorgängen und Katalog.','Unterstützt .xlsx, .xls und .csv. Vorhandene Treffer werden übersprungen und nicht überschrieben.','Tabelle wird gelesen…','Excel wird vorbereitet…','Vorlage wird vorbereitet…'],
 es:['Importar Excel','Exportar Excel','Importar contactos','Importar catálogo','Exportar todo a Excel','Plantilla de contactos','Plantilla de catálogo','IMPORTAR Y EXPORTAR DATOS','Mueve los datos de tu negocio','Importa clientes, leads o elementos del catálogo desde Excel. Exporta un libro con clientes, leads, facturas, presupuestos, trabajos recurrentes y catálogo.','Admite .xlsx, .xls y .csv. Los registros existentes se omiten y no se sobrescriben.','Leyendo la hoja…','Preparando Excel…','Preparando plantilla…'],
 fr:['Importer Excel','Exporter Excel','Importer des contacts','Importer le catalogue','Tout exporter vers Excel','Modèle de contacts','Modèle de catalogue','IMPORT ET EXPORT DE DONNÉES','Importez ou exportez vos données','Importez des clients, prospects ou éléments de catalogue depuis Excel. Exportez un classeur avec clients, prospects, factures, devis, travaux récurrents et catalogue.','Accepte .xlsx, .xls et .csv. Les correspondances existantes sont ignorées et ne sont pas écrasées.','Lecture du tableur…','Préparation d’Excel…','Préparation du modèle…']
}[['en','no','sv','de','es','fr'].includes(lang)?lang:'en'];
const [importExcel,exportExcel,importContacts,importCatalog,exportAll,contactsTemplate,catalogTemplate,eyebrow,title,body,hint,reading,exporting,templating]=C;

function msg(type,r){
 const n=r.imported,d=r.duplicates;
 const t={
  en:type==='catalog'?`${n} catalog item${n===1?'':'s'} imported · ${d} duplicate${d===1?'':'s'} skipped`:`${n} contact${n===1?'':'s'} imported · ${d} duplicate${d===1?'':'s'} skipped`,
  no:type==='catalog'?`${n} katalogelement${n===1?'':'er'} importert · ${d} duplikat${d===1?'':'er'} hoppet over`:`${n} kontakt${n===1?'':'er'} importert · ${d} duplikat${d===1?'':'er'} hoppet over`,
  sv:type==='catalog'?`${n} katalogpost${n===1?'':'er'} importerade · ${d} dubblett${d===1?'':'er'} hoppades över`:`${n} kontakt${n===1?'':'er'} importerade · ${d} dubblett${d===1?'':'er'} hoppades över`,
  de:type==='catalog'?`${n} Katalogeintrag${n===1?'':'e'} importiert · ${d} Duplikat${d===1?'':'e'} übersprungen`:`${n} Kontakt${n===1?'':'e'} importiert · ${d} Duplikat${d===1?'':'e'} übersprungen`,
  es:type==='catalog'?`${n} elemento${n===1?'':'s'} del catálogo importados · ${d} duplicado${d===1?'':'s'} omitidos`:`${n} contacto${n===1?'':'s'} importados · ${d} duplicado${d===1?'':'s'} omitidos`,
  fr:type==='catalog'?`${n} élément${n===1?'':'s'} de catalogue importés · ${d} doublon${d===1?'':'s'} ignorés`:`${n} contact${n===1?'':'s'} importés · ${d} doublon${d===1?'':'s'} ignorés`
 };
 return t[lang]||t.en;
}
function toast(text,tone='success'){if(window.sbkToast)return window.sbkToast(text,tone);const e=document.createElement('div');e.className='spreadsheet-toast';e.textContent=text;document.body.appendChild(e);setTimeout(()=>e.remove(),3500)}
function busy(b,text){const old=b.textContent;b.disabled=true;b.textContent=text;return()=>{b.disabled=false;b.textContent=old}}
function pickFile(){return new Promise(resolve=>{const i=document.createElement('input');i.type='file';i.accept='.xlsx,.xls,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv';i.hidden=true;i.onchange=()=>{const f=i.files?.[0]||null;i.remove();resolve(f)};document.body.appendChild(i);i.click()})}
async function runImport(kind,b){const f=await pickFile();if(!f)return;const done=busy(b,reading);try{const p=await previewSpreadsheetImport(f,kind);const q=lang==='no'?`Importer ${p.validRows} rader fra «${p.sheetName}»? Eksisterende treff hoppes over.`:`Import ${p.validRows} rows from “${p.sheetName}”? Existing matches will be skipped.`;if(!confirm(q))return;const r=await commitSpreadsheetImport(p);toast(msg(kind,r));window.dispatchEvent(new CustomEvent('solobizkit:workspace-updated',{detail:{source:'spreadsheet-import',kind,result:r}}));setTimeout(()=>location.reload(),700)}catch(e){console.error(e);alert(e?.message||'Could not import spreadsheet.')}finally{done()}}
async function runExport(b){const done=busy(b,exporting);try{await exportWorkspaceExcel();toast(lang==='no'?'Excel-eksport lastet ned.':'Excel export downloaded.')}catch(e){console.error(e);alert(e?.message||'Could not export Excel.')}finally{done()}}
async function runTemplate(kind,b){const done=busy(b,templating);try{await downloadSpreadsheetTemplate(kind);toast(lang==='no'?'Excel-mal lastet ned.':'Excel template downloaded.')}catch(e){alert(e?.message||'Could not create template.')}finally{done()}}
function bind(b,fn){if(!b||b.dataset.xlsxBound)return;b.dataset.xlsxBound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn(b)},true)}
function btn(text,id,cls='btn secondary'){const b=document.createElement('button');b.type='button';b.id=id;b.className=cls;b.textContent=text;return b}
function leads(){const i=document.querySelector('#importCsv'),e=document.querySelector('#exportCsv');if(!i||!e)return;i.textContent=importExcel;e.textContent=exportExcel;const f=document.querySelector('#csvInput');if(f)f.accept='.xlsx,.xls,.csv';bind(i,b=>runImport('contacts',b));bind(e,runExport)}
function catalog(){const n=document.querySelector('#newProduct');if(!n||n.hidden||document.querySelector('#xlsxCatalogImport'))return;const i=btn(importExcel,'xlsxCatalogImport'),e=btn(exportExcel,'xlsxCatalogExport');n.parentElement.insertBefore(i,n);n.parentElement.insertBefore(e,n);bind(i,b=>runImport('catalog',b));bind(e,runExport)}
function customers(){const t=document.querySelector('#pageTitle')?.textContent?.trim();if(!['Customers','Kunder','Kunden','Clientes','Clients'].includes(t))return;const bar=document.querySelector('#app .toolbar'),n=document.querySelector('#newCustomer');if(!bar||!n||bar.querySelector('#xlsxCustomerImport'))return;const i=btn(importExcel,'xlsxCustomerImport'),e=btn(exportExcel,'xlsxCustomerExport');bar.insertBefore(i,n);bar.insertBefore(e,n);bind(i,b=>runImport('contacts',b));bind(e,runExport)}
function settings(){const g=document.querySelector('#app .settings-grid');if(!g||g.querySelector('[data-xlsx-settings]'))return;const s=document.createElement('section');s.className='settings-card spreadsheet-settings-card';s.dataset.xlsxSettings='1';s.innerHTML=`<div class="split"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div><span class="status paid">XLSX</span></div><p class="muted spreadsheet-settings-copy">${body}</p><div class="spreadsheet-tool-grid"><div class="spreadsheet-tool"><strong>${importContacts}</strong><span>${hint}</span><div><button class="btn secondary" data-import-contacts>${importContacts}</button><button class="mini-btn" data-template-contacts>${contactsTemplate}</button></div></div><div class="spreadsheet-tool"><strong>${importCatalog}</strong><span>${hint}</span><div><button class="btn secondary" data-import-catalog>${importCatalog}</button><button class="mini-btn" data-template-catalog>${catalogTemplate}</button></div></div><div class="spreadsheet-tool spreadsheet-tool-export"><strong>${exportAll}</strong><span>${body}</span><div><button class="btn primary" data-export-all>${exportAll}</button></div></div></div>`;g.appendChild(s);bind(s.querySelector('[data-import-contacts]'),b=>runImport('contacts',b));bind(s.querySelector('[data-import-catalog]'),b=>runImport('catalog',b));bind(s.querySelector('[data-template-contacts]'),b=>runTemplate('contacts',b));bind(s.querySelector('[data-template-catalog]'),b=>runTemplate('catalog',b));bind(s.querySelector('[data-export-all]'),runExport)}
function enhance(){const p=location.pathname;if(p.startsWith('/pro/leads'))leads();else if(p.startsWith('/pro/catalog'))catalog();else if(p.startsWith('/pro/settings'))settings();else customers()}
const style=document.createElement('style');style.textContent='.spreadsheet-settings-card{grid-column:1/-1}.spreadsheet-tool-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:18px}.spreadsheet-tool{border:1px solid var(--line);border-radius:14px;background:#fafbfc;padding:15px;display:grid;gap:9px}.spreadsheet-tool>span{font-size:11px;line-height:1.5;color:var(--muted)}.spreadsheet-tool>div{display:flex;gap:7px;flex-wrap:wrap}.spreadsheet-tool-export{background:linear-gradient(135deg,#f7faff,#eef4ff);border-color:#cddcff}.spreadsheet-toast{position:fixed;right:20px;bottom:20px;z-index:9999;background:#0c1b38;color:#fff;border-radius:13px;padding:13px 15px;box-shadow:0 20px 50px rgba(7,20,47,.28);font-size:12px;font-weight:700}@media(max-width:900px){.spreadsheet-tool-grid{grid-template-columns:1fr}}';document.head.appendChild(style);
let q=false;new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;enhance()})}).observe(document.body,{childList:true,subtree:true,characterData:true});enhance();