import { getSession, getWorkspaceContext, setActiveWorkspace, supabase } from './backend.js';

const lang=(()=>{try{return localStorage.getItem('sbk_language')||'en'}catch{return'en'}})();
const COPY={
  en:{eyebrow:'TEAM ACCESS',title:'People in this workspace',body:'Invite employees or your accountant without sharing the owner password.',invite:'Invite user',email:'Email address',role:'Role',owner:'Owner',admin:'Admin',member:'Member',accountant:'Accountant',pending:'Pending invitations',joined:'Workspace members',remove:'Remove',cancel:'Cancel invite',sending:'Sending invite…',sent:'Invitation sent.',none:'No additional members yet.',nonePending:'No pending invitations.',switchLabel:'Active workspace',save:'Change role',adminHint:'Admins can manage settings and team members. Members can create and edit business data. Accountants have read-only access.',ownerOnly:'Only workspace owners and admins can manage team access.'},
  no:{eyebrow:'TEAMTILGANG',title:'Personer i arbeidsområdet',body:'Inviter ansatte eller regnskapsfører uten å dele eierens passord.',invite:'Inviter bruker',email:'E-postadresse',role:'Rolle',owner:'Eier',admin:'Admin',member:'Medlem',accountant:'Regnskapsfører',pending:'Ventende invitasjoner',joined:'Medlemmer',remove:'Fjern',cancel:'Trekk invitasjon',sending:'Sender invitasjon…',sent:'Invitasjon sendt.',none:'Ingen ekstra medlemmer ennå.',nonePending:'Ingen ventende invitasjoner.',switchLabel:'Aktivt arbeidsområde',save:'Endre rolle',adminHint:'Admin kan endre innstillinger og administrere teamet. Medlem kan opprette og redigere data. Regnskapsfører har lesetilgang.',ownerOnly:'Bare eier og admin kan administrere teamtilgang.'},
  sv:{eyebrow:'TEAMÅTKOMST',title:'Personer i arbetsytan',body:'Bjud in anställda eller redovisningskonsult utan att dela ägarens lösenord.',invite:'Bjud in användare',email:'E-postadress',role:'Roll',owner:'Ägare',admin:'Admin',member:'Medlem',accountant:'Redovisning',pending:'Väntande inbjudningar',joined:'Medlemmar',remove:'Ta bort',cancel:'Återkalla inbjudan',sending:'Skickar inbjudan…',sent:'Inbjudan skickad.',none:'Inga extra medlemmar ännu.',nonePending:'Inga väntande inbjudningar.',switchLabel:'Aktiv arbetsyta',save:'Ändra roll',adminHint:'Admins kan hantera inställningar och team. Medlemmar kan skapa och redigera data. Redovisning har läsbehörighet.',ownerOnly:'Endast ägare och admins kan hantera teamåtkomst.'},
  de:{eyebrow:'TEAMZUGRIFF',title:'Personen im Arbeitsbereich',body:'Lade Mitarbeitende oder die Buchhaltung ein, ohne das Besitzer-Passwort zu teilen.',invite:'Benutzer einladen',email:'E-Mail-Adresse',role:'Rolle',owner:'Inhaber',admin:'Admin',member:'Mitglied',accountant:'Buchhaltung',pending:'Ausstehende Einladungen',joined:'Mitglieder',remove:'Entfernen',cancel:'Einladung widerrufen',sending:'Einladung wird gesendet…',sent:'Einladung gesendet.',none:'Noch keine weiteren Mitglieder.',nonePending:'Keine ausstehenden Einladungen.',switchLabel:'Aktiver Arbeitsbereich',save:'Rolle ändern',adminHint:'Admins verwalten Einstellungen und Team. Mitglieder können Daten erstellen und bearbeiten. Buchhaltung hat Lesezugriff.',ownerOnly:'Nur Inhaber und Admins können den Teamzugriff verwalten.'},
  es:{eyebrow:'ACCESO DEL EQUIPO',title:'Personas del espacio de trabajo',body:'Invita empleados o a tu contable sin compartir la contraseña del propietario.',invite:'Invitar usuario',email:'Correo electrónico',role:'Rol',owner:'Propietario',admin:'Admin',member:'Miembro',accountant:'Contable',pending:'Invitaciones pendientes',joined:'Miembros',remove:'Eliminar',cancel:'Cancelar invitación',sending:'Enviando invitación…',sent:'Invitación enviada.',none:'Todavía no hay miembros adicionales.',nonePending:'No hay invitaciones pendientes.',switchLabel:'Espacio de trabajo activo',save:'Cambiar rol',adminHint:'Los admins gestionan ajustes y equipo. Los miembros pueden crear y editar datos. Los contables tienen acceso de lectura.',ownerOnly:'Solo propietarios y admins pueden gestionar el acceso del equipo.'},
  fr:{eyebrow:'ACCÈS ÉQUIPE',title:'Personnes dans cet espace',body:'Invitez des employés ou votre comptable sans partager le mot de passe du propriétaire.',invite:'Inviter un utilisateur',email:'Adresse e-mail',role:'Rôle',owner:'Propriétaire',admin:'Admin',member:'Membre',accountant:'Comptable',pending:'Invitations en attente',joined:'Membres',remove:'Supprimer',cancel:"Annuler l’invitation",sending:'Envoi de l’invitation…',sent:'Invitation envoyée.',none:'Aucun membre supplémentaire.',nonePending:'Aucune invitation en attente.',switchLabel:'Espace actif',save:'Changer le rôle',adminHint:'Les admins gèrent les réglages et l’équipe. Les membres peuvent créer et modifier les données. Les comptables ont un accès en lecture.',ownerOnly:'Seuls le propriétaire et les admins peuvent gérer l’accès équipe.'}
};
const t=COPY[lang]||COPY.en;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const roleLabel=role=>t[role]||role;
let context=null,session=null,rendering=false;

async function loadTeam(){
  const [teamResult,inviteResult]=await Promise.all([
    supabase.rpc('get_workspace_team'),
    supabase.from('workspace_invitations').select('id,email,role,expires_at,created_at').eq('workspace_id',context.workspaceId).is('accepted_at',null).order('created_at',{ascending:false})
  ]);
  if(teamResult.error)throw teamResult.error;
  if(inviteResult.error)throw inviteResult.error;
  return {members:teamResult.data||[],invites:inviteResult.data||[]};
}

function memberRow(m){
  const editable=context.canAdmin&&!m.is_owner&&m.user_id!==session.user.id;
  return `<div class="team-person"><div class="team-avatar">${esc((m.full_name||m.email||'?').slice(0,1).toUpperCase())}</div><div class="team-person-copy"><strong>${esc(m.full_name||m.email||'Member')}</strong>${m.full_name&&m.email?`<span>${esc(m.email)}</span>`:''}</div><div class="team-person-role">${editable?`<select class="select" data-team-role="${esc(m.user_id)}"><option value="admin" ${m.role==='admin'?'selected':''}>${esc(t.admin)}</option><option value="member" ${m.role==='member'?'selected':''}>${esc(t.member)}</option><option value="accountant" ${m.role==='accountant'?'selected':''}>${esc(t.accountant)}</option></select>`:`<span class="status ${m.role==='owner'?'paid':'draft'}">${esc(roleLabel(m.role))}</span>`}</div>${editable?`<button class="mini-btn" type="button" data-remove-member="${esc(m.user_id)}">${esc(t.remove)}</button>`:''}</div>`;
}
function inviteRow(i){return `<div class="team-person team-invite"><div class="team-avatar">@</div><div class="team-person-copy"><strong>${esc(i.email)}</strong><span>${esc(roleLabel(i.role))} · ${esc(new Date(i.expires_at).toLocaleDateString())}</span></div><span class="status draft">${esc(t.pending)}</span>${context.canAdmin?`<button class="mini-btn" type="button" data-cancel-invite="${esc(i.id)}">${esc(t.cancel)}</button>`:''}</div>`;}

async function render(){
  if(rendering)return;const grid=document.querySelector('#app .settings-grid');if(!grid||grid.querySelector('[data-team-access]'))return;
  rendering=true;
  try{
    session=await getSession();if(!session)return;context=await getWorkspaceContext(true);if(!context)return;
    const {members,invites}=await loadTeam();
    const section=document.createElement('section');section.className='settings-card team-access-card';section.dataset.teamAccess='1';
    section.innerHTML=`<div class="split"><div><p class="eyebrow">${esc(t.eyebrow)}</p><h2>${esc(t.title)}</h2></div><span class="status paid">${members.length}</span></div><p class="muted">${esc(t.body)}</p>${context.canAdmin?`<form class="team-invite-form" data-team-invite-form><div class="field"><label>${esc(t.email)}</label><input class="input" name="email" type="email" required placeholder="name@company.com"></div><div class="field"><label>${esc(t.role)}</label><select class="select" name="role"><option value="member">${esc(t.member)}</option><option value="admin">${esc(t.admin)}</option><option value="accountant">${esc(t.accountant)}</option></select></div><button class="btn primary" type="submit">${esc(t.invite)}</button><span class="save-state" data-team-message></span></form>`:`<div class="paywall-notice">${esc(t.ownerOnly)}</div>`}<p class="muted team-role-hint">${esc(t.adminHint)}</p><div class="team-section"><h3>${esc(t.joined)}</h3><div class="team-list">${members.length?members.map(memberRow).join(''):`<div class="empty">${esc(t.none)}</div>`}</div></div><div class="team-section"><h3>${esc(t.pending)}</h3><div class="team-list">${invites.length?invites.map(inviteRow).join(''):`<div class="empty">${esc(t.nonePending)}</div>`}</div></div>`;
    grid.appendChild(section);
    const form=section.querySelector('[data-team-invite-form]');
    if(form)form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),button=form.querySelector('button[type="submit"]'),msg=form.querySelector('[data-team-message]');button.disabled=true;msg.textContent=t.sending;try{const{data,error}=await supabase.functions.invoke('workspace-invite',{body:{email:String(fd.get('email')||'').trim(),role:String(fd.get('role')||'member')}});if(error)throw error;if(data?.error)throw new Error(data.error);msg.textContent=t.sent;window.sbkTrack?.('workspace_member_invited',{role:String(fd.get('role')||'member')});setTimeout(()=>{section.remove();render();},400);}catch(error){console.error(error);msg.textContent=error?.message||'Could not send invitation.';button.disabled=false;}});
    section.querySelectorAll('[data-team-role]').forEach(select=>select.addEventListener('change',async()=>{select.disabled=true;try{const{error}=await supabase.rpc('update_workspace_member_role',{p_user_id:select.dataset.teamRole,p_role:select.value});if(error)throw error;window.sbkTrack?.('workspace_member_role_changed',{role:select.value});}catch(error){alert(error.message||'Could not change role.');}finally{select.disabled=false;}}));
    section.querySelectorAll('[data-remove-member]').forEach(button=>button.addEventListener('click',async()=>{if(!confirm(`${t.remove}?`))return;button.disabled=true;try{const{error}=await supabase.rpc('remove_workspace_member',{p_user_id:button.dataset.removeMember});if(error)throw error;section.remove();render();}catch(error){alert(error.message||'Could not remove member.');button.disabled=false;}}));
    section.querySelectorAll('[data-cancel-invite]').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;try{const{error}=await supabase.rpc('cancel_workspace_invitation',{p_invite_id:button.dataset.cancelInvite});if(error)throw error;section.remove();render();}catch(error){alert(error.message||'Could not cancel invitation.');button.disabled=false;}}));
  }catch(error){console.error('[Team access]',error);}
  finally{rendering=false;}
}

const style=document.createElement('style');style.textContent='.team-access-card{grid-column:1/-1}.team-invite-form{display:grid;grid-template-columns:minmax(220px,1fr) 180px auto;align-items:end;gap:10px;margin:18px 0}.team-invite-form .save-state{grid-column:1/-1}.team-section{margin-top:22px}.team-section h3{font-size:13px;margin-bottom:9px}.team-list{display:grid;gap:8px}.team-person{display:grid;grid-template-columns:36px minmax(0,1fr) minmax(110px,190px) auto;gap:10px;align-items:center;padding:10px 12px;border:1px solid var(--line);border-radius:12px;background:#fafbfc}.team-avatar{width:34px;height:34px;border-radius:10px;background:#edf3ff;color:#2457f5;display:grid;place-items:center;font-weight:900}.team-person-copy{min-width:0}.team-person-copy strong,.team-person-copy span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.team-person-copy strong{font-size:12px}.team-person-copy span{font-size:10px;color:var(--muted);margin-top:2px}.team-person-role .select{padding:7px 28px 7px 9px;font-size:11px}.team-role-hint{font-size:11px;line-height:1.55}.team-invite{background:#fff}@media(max-width:760px){.team-invite-form{grid-template-columns:1fr}.team-invite-form .save-state{grid-column:auto}.team-person{grid-template-columns:36px minmax(0,1fr)}.team-person-role,.team-person>button,.team-person>.status{grid-column:2}}';document.head.appendChild(style);
new MutationObserver(()=>render()).observe(document.querySelector('#app'),{childList:true,subtree:true});
render();
