import { getDataOwnerId, getSession, getWorkspaceContext, loadWorkspace, supabase } from './backend.js';

const app=document.querySelector('#app');
const pageTitle=document.querySelector('#pageTitle');
let cache=null,context=null,dataOwner=null,session=null;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]);
const today=()=>new Date().toISOString().slice(0,10);
const language=()=>{try{return ['en','no','sv','de','es','fr'].includes(localStorage.getItem('sbk_language'))?localStorage.getItem('sbk_language'):'en'}catch{return'en'}};
const T={
  en:{eye:'TODAY',title:'Your day',sub:'Automatic follow-ups and the opportunities most worth your attention.',pipeline:'Open pipeline',due:'tasks due',high:'high priority',hot:'hot leads',warm:'warm leads',hotTitle:'Hot opportunities',overdue:'Overdue',dueLabel:'Due',done:'Done',tomorrow:'Tomorrow','3d':'+3 days',empty:'Nothing needs attention today.',customer:'Customer',snoozeFail:'Could not snooze task.',doneFail:'Could not complete task.'},
  no:{eye:'I DAG',title:'Dagen din',sub:'Automatiske oppfølginger og mulighetene som fortjener mest oppmerksomhet.',pipeline:'Åpne pipeline',due:'oppgaver forfaller',high:'høy prioritet',hot:'varme leads',warm:'lunkne leads',hotTitle:'Varmeste muligheter',overdue:'Forfalt',dueLabel:'Forfall',done:'Ferdig',tomorrow:'I morgen','3d':'+3 dager',empty:'Ingenting krever oppmerksomhet i dag.',customer:'Kunde',snoozeFail:'Kunne ikke utsette oppgaven.',doneFail:'Kunne ikke fullføre oppgaven.'},
  sv:{eye:'IDAG',title:'Din dag',sub:'Automatiska uppföljningar och möjligheterna som förtjänar mest uppmärksamhet.',pipeline:'Öppna pipeline',due:'uppgifter förfaller',high:'hög prioritet',hot:'heta leads',warm:'varma leads',hotTitle:'Hetaste möjligheterna',overdue:'Förfallen',dueLabel:'Förfall',done:'Klar',tomorrow:'I morgon','3d':'+3 dagar',empty:'Inget kräver din uppmärksamhet idag.',customer:'Kund',snoozeFail:'Kunde inte skjuta upp uppgiften.',doneFail:'Kunde inte slutföra uppgiften.'},
  de:{eye:'HEUTE',title:'Ihr Tag',sub:'Automatische Follow-ups und die Chancen, die heute am wichtigsten sind.',pipeline:'Pipeline öffnen',due:'Aufgaben fällig',high:'hohe Priorität',hot:'heiße Leads',warm:'warme Leads',hotTitle:'Top-Chancen',overdue:'Überfällig',dueLabel:'Fällig',done:'Erledigt',tomorrow:'Morgen','3d':'+3 Tage',empty:'Heute ist nichts Dringendes zu erledigen.',customer:'Kunde',snoozeFail:'Aufgabe konnte nicht verschoben werden.',doneFail:'Aufgabe konnte nicht abgeschlossen werden.'},
  es:{eye:'HOY',title:'Tu día',sub:'Seguimientos automáticos y las oportunidades que más merecen tu atención.',pipeline:'Abrir pipeline',due:'tareas vencen',high:'alta prioridad',hot:'leads calientes',warm:'leads templados',hotTitle:'Mejores oportunidades',overdue:'Vencida',dueLabel:'Vence',done:'Hecho',tomorrow:'Mañana','3d':'+3 días',empty:'Nada requiere atención hoy.',customer:'Cliente',snoozeFail:'No se pudo aplazar la tarea.',doneFail:'No se pudo completar la tarea.'},
  fr:{eye:"AUJOURD’HUI",title:'Votre journée',sub:'Suivis automatiques et opportunités qui méritent le plus votre attention.',pipeline:'Ouvrir le pipeline',due:'tâches à faire',high:'haute priorité',hot:'leads chauds',warm:'leads tièdes',hotTitle:'Meilleures opportunités',overdue:'En retard',dueLabel:'Échéance',done:'Terminé',tomorrow:'Demain','3d':'+3 jours',empty:'Rien ne demande votre attention aujourd’hui.',customer:'Client',snoozeFail:'Impossible de reporter la tâche.',doneFail:'Impossible de terminer la tâche.'}
};
const t=k=>T[language()]?.[k]||T.en[k]||k;
function customerName(data,id){return data.customers.find(c=>c.id===id)?.name||t('customer')}
function taskHref(task){if(task.related_type==='estimate'&&task.related_id)return`/pro/estimates/?estimate=${encodeURIComponent(task.related_id)}`;if(task.related_type==='invoice'&&task.related_id)return`/pro/?view=invoices&invoice=${encodeURIComponent(task.related_id)}`;if(task.related_type==='deal'&&task.related_id)return`/pro/pipeline/?deal=${encodeURIComponent(task.related_id)}`;if(task.deal_id)return`/pro/pipeline/?deal=${encodeURIComponent(task.deal_id)}`;if(task.customer_id)return`/pro/?view=customers&customer=${encodeURIComponent(task.customer_id)}`;return'/pro/pipeline/'}
async function syncAutomation(){if(!context?.canWrite)return;const{error}=await supabase.rpc('sync_crm_automation');if(error)console.warn('Today CRM automation sync skipped',error)}
async function data(force=false){session||=await getSession();if(!session?.user?.id)return null;if(force||!cache){context=await getWorkspaceContext(true);dataOwner=await getDataOwnerId();await syncAutomation();const workspace=await loadWorkspace(session.user.id);const[tasks,deals]=await Promise.all([supabase.from('crm_tasks').select('*').eq('user_id',dataOwner).is('completed_at',null).order('due_date',{ascending:true}),supabase.from('crm_deals').select('id,customer_id,title,stage,lead_score,score_reasons,last_engaged_at').eq('user_id',dataOwner).not('stage','in','(won,lost)').order('lead_score',{ascending:false}).limit(8)]);if(tasks.error)throw tasks.error;if(deals.error)throw deals.error;cache={...workspace,tasks:tasks.data||[],deals:deals.data||[]}}return cache}
function priorityRank(task){const overdue=task.due_date&&task.due_date<today();if(overdue&&task.priority==='high')return 0;if(overdue)return 1;if(task.priority==='high')return 2;if(task.priority==='normal')return 3;return 4}
function dueItems(d){return d.tasks.map(task=>({kind:'task',id:task.id,tone:task.priority==='high'||task.due_date<today()?'danger':'normal',title:task.title,detail:`${customerName(d,task.customer_id)} · ${task.due_date<today()?t('overdue'):t('dueLabel')} ${task.due_date||'—'}`,href:taskHref(task),rank:priorityRank(task),due:task.due_date||'9999-12-31'})).sort((a,b)=>a.rank-b.rank||a.due.localeCompare(b.due)).slice(0,8)}
async function completeTask(id){if(!context?.canWrite)return;const{error}=await supabase.from('crm_tasks').update({completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',dataOwner);if(error)throw error;refresh()}
async function snoozeTask(id,days){if(!context?.canWrite)return;const d=new Date();d.setDate(d.getDate()+days);const due=d.toISOString().slice(0,10);const{error}=await supabase.from('crm_tasks').update({due_date:due,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',dataOwner);if(error)throw error;refresh()}
function refresh(){cache=null;document.querySelector('.today-center')?.remove();enhance()}
function inject(d){if(pageTitle?.textContent!=='Dashboard'||app.querySelector('.today-center'))return;const target=app.querySelector('.dashboard-v2')||app.querySelector('.stats');if(!target)return;const items=dueItems(d);const dueTasks=d.tasks.filter(x=>x.due_date&&x.due_date<=today()).length;const highPriority=d.tasks.filter(x=>x.priority==='high').length;const hot=d.deals.filter(deal=>Number(deal.lead_score||0)>=75);const warm=d.deals.filter(deal=>Number(deal.lead_score||0)>=45&&Number(deal.lead_score||0)<75);const wrap=document.createElement('section');wrap.className='card today-center';wrap.innerHTML=`<div class="card-head"><div><p class="eyebrow">${esc(t('eye'))}</p><h2>${esc(t('title'))}</h2><p class="muted">${esc(t('sub'))}</p></div><a class="mini-btn" href="/pro/pipeline/">${esc(t('pipeline'))}</a></div><div class="today-stats"><span><b>${dueTasks}</b> ${esc(t('due'))}</span><span><b>${highPriority}</b> ${esc(t('high'))}</span><span><b>${hot.length}</b> ${esc(t('hot'))}</span><span><b>${warm.length}</b> ${esc(t('warm'))}</span></div>${hot.length?`<div class="today-hot"><strong>${esc(t('hotTitle'))}</strong>${hot.slice(0,3).map(deal=>`<a href="/pro/pipeline/?deal=${encodeURIComponent(deal.id)}"><span>${esc(deal.title)}</span><b>${Number(deal.lead_score||0)}/100</b></a>`).join('')}</div>`:''}<div class="today-list">${items.length?items.map(i=>`<div class="today-item ${i.tone}"><a href="${i.href}"><strong>${esc(i.title)}</strong><small>${esc(i.detail)}</small></a>${context?.canWrite?`<div class="today-task-actions"><button class="mini-btn" data-snooze-task="${i.id}" data-days="1">${esc(t('tomorrow'))}</button><button class="mini-btn" data-snooze-task="${i.id}" data-days="3">${esc(t('3d'))}</button><button class="mini-btn" data-complete-task="${i.id}">${esc(t('done'))}</button></div>`:''}</div>`).join(''):`<div class="empty compact-empty">${esc(t('empty'))}</div>`}</div>`;target.insertAdjacentElement('afterend',wrap);wrap.querySelectorAll('[data-complete-task]').forEach(b=>b.onclick=()=>completeTask(b.dataset.completeTask).catch(e=>alert(e.message||t('doneFail'))));wrap.querySelectorAll('[data-snooze-task]').forEach(b=>b.onclick=()=>snoozeTask(b.dataset.snoozeTask,Number(b.dataset.days||1)).catch(e=>alert(e.message||t('snoozeFail'))))}
function style(){if(document.querySelector('#todayCenterStyle'))return;const s=document.createElement('style');s.id='todayCenterStyle';s.textContent='.today-center{margin-top:18px}.today-center .card-head{align-items:flex-start}.today-stats{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.today-stats span{padding:8px 10px;border-radius:999px;background:#f4f7fb;font-size:12px;color:#5f6c80}.today-stats b{color:#111827}.today-hot{display:grid;gap:7px;margin:0 0 14px;padding:12px;border-radius:13px;background:#fff8f8;border:1px solid #f3d1d1}.today-hot>strong{font-size:12px}.today-hot a{display:flex;align-items:center;justify-content:space-between;gap:10px;text-decoration:none;color:inherit;font-size:12px}.today-hot a b{color:#a61b1b}.today-list{display:grid;gap:8px}.today-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:12px;border:1px solid #e8ebf0;border-radius:12px}.today-item.danger{border-color:#f4c7c7;background:#fffafa}.today-item a{text-decoration:none;color:inherit}.today-item strong,.today-item small{display:block}.today-item small{margin-top:3px;color:#6b7280;font-size:12px}.today-task-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}@media(max-width:700px){.today-item{grid-template-columns:1fr}.today-task-actions{justify-content:stretch}.today-task-actions .mini-btn{flex:1}}';document.head.appendChild(s)}
async function enhance(){style();if(pageTitle?.textContent!=='Dashboard')return;try{const d=await data();if(d)inject(d)}catch(e){console.warn('Today center skipped',e)}}
new MutationObserver(()=>requestAnimationFrame(enhance)).observe(app,{childList:true,subtree:true});window.addEventListener('focus',refresh);window.addEventListener('solobizkit:workspace-updated',refresh);window.addEventListener('storage',e=>{if(e.key==='sbk_language')refresh()});enhance();