import { getDataOwnerId, getSession, getWorkspaceContext, loadWorkspace, supabase } from './backend.js';

const app=document.querySelector('#app');
const pageTitle=document.querySelector('#pageTitle');
let cache=null,context=null,dataOwner=null,session=null;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]);
const today=()=>new Date().toISOString().slice(0,10);
const daysAgo=(n)=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};
function customerName(data,id){return data.customers.find(c=>c.id===id)?.name||'Customer'}
function status(invoice){const s=String(invoice.status||'draft').toLowerCase();if(s==='sent'&&invoice.dueDate&&invoice.dueDate<today())return'overdue';return s}
async function data(force=false){session||=await getSession();if(!session?.user?.id)return null;if(force||!cache){context=await getWorkspaceContext(true);dataOwner=await getDataOwnerId();const workspace=await loadWorkspace(session.user.id);const tasks=await supabase.from('crm_tasks').select('*').eq('user_id',dataOwner).is('completed_at',null).order('due_date',{ascending:true});if(tasks.error)throw tasks.error;cache={...workspace,tasks:tasks.data||[]}}return cache}
function dueItems(d){const items=[];for(const task of d.tasks){items.push({kind:'task',id:task.id,tone:task.due_date<today()?'danger':'normal',title:task.title,detail:`${customerName(d,task.customer_id)} · ${task.due_date<today()?'Overdue':'Due'} ${task.due_date}`,href:task.customer_id?`/pro/?view=customers&customer=${encodeURIComponent(task.customer_id)}`:'/pro/pipeline/'})}for(const inv of d.invoices.filter(i=>status(i)==='overdue'))items.push({kind:'invoice',id:inv.id,tone:'danger',title:`Invoice ${inv.number} is overdue`,detail:`${customerName(d,inv.customerId)} · due ${inv.dueDate||'—'}`,href:`/pro/?view=invoices&invoice=${encodeURIComponent(inv.id)}`});for(const est of d.estimates.filter(e=>String(e.status).toLowerCase()==='sent'&&String(e.updatedAt||e.issueDate||'')<daysAgo(3)))items.push({kind:'estimate',id:est.id,tone:'normal',title:`Follow up on ${est.number}`,detail:`${customerName(d,est.customerId)} · estimate sent`,href:`/pro/estimates/?estimate=${encodeURIComponent(est.id)}`});return items.sort((a,b)=>(a.tone==='danger'?-1:1)-(b.tone==='danger'?-1:1)).slice(0,8)}
async function completeTask(id){if(!context?.canWrite)return;const{error}=await supabase.from('crm_tasks').update({completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',dataOwner);if(error)throw error;cache=null;enhance()}
function inject(d){if(pageTitle?.textContent!=='Dashboard'||app.querySelector('.today-center'))return;const target=app.querySelector('.dashboard-v2')||app.querySelector('.stats');if(!target)return;const items=dueItems(d);const dueTasks=d.tasks.filter(t=>t.due_date<=today()).length;const overdueInvoices=d.invoices.filter(i=>status(i)==='overdue').length;const staleEstimates=d.estimates.filter(e=>String(e.status).toLowerCase()==='sent'&&String(e.updatedAt||e.issueDate||'')<daysAgo(3)).length;const wrap=document.createElement('section');wrap.className='card today-center';wrap.innerHTML=`<div class="card-head"><div><p class="eyebrow">TODAY</p><h2>Your day</h2><p class="muted">Tasks, overdue invoices and estimates worth following up.</p></div><a class="mini-btn" href="/pro/pipeline/">Open pipeline</a></div><div class="today-stats"><span><b>${dueTasks}</b> tasks due</span><span><b>${overdueInvoices}</b> overdue invoices</span><span><b>${staleEstimates}</b> estimates to follow up</span></div><div class="today-list">${items.length?items.map(i=>`<div class="today-item ${i.tone}"><a href="${i.href}"><strong>${esc(i.title)}</strong><small>${esc(i.detail)}</small></a>${i.kind==='task'&&context?.canWrite?`<button class="mini-btn" data-complete-task="${i.id}">Done</button>`:''}</div>`).join(''):'<div class="empty compact-empty">Nothing needs attention today.</div>'}</div>`;target.insertAdjacentElement('afterend',wrap);wrap.querySelectorAll('[data-complete-task]').forEach(b=>b.onclick=()=>completeTask(b.dataset.completeTask).catch(e=>alert(e.message||'Could not complete task.')))}
function style(){if(document.querySelector('#todayCenterStyle'))return;const s=document.createElement('style');s.id='todayCenterStyle';s.textContent='.today-center{margin-top:18px}.today-center .card-head{align-items:flex-start}.today-stats{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.today-stats span{padding:8px 10px;border-radius:999px;background:#f4f7fb;font-size:12px;color:#5f6c80}.today-stats b{color:#111827}.today-list{display:grid;gap:8px}.today-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:12px;border:1px solid #e8ebf0;border-radius:12px}.today-item.danger{border-color:#f4c7c7;background:#fffafa}.today-item a{text-decoration:none;color:inherit}.today-item strong,.today-item small{display:block}.today-item small{margin-top:3px;color:#6b7280;font-size:12px}@media(max-width:600px){.today-item{grid-template-columns:1fr}.today-item .mini-btn{width:100%}}';document.head.appendChild(s)}
async function enhance(){style();if(pageTitle?.textContent!=='Dashboard')return;try{const d=await data();if(d)inject(d)}catch(e){console.warn('Today center skipped',e)}}
new MutationObserver(()=>requestAnimationFrame(enhance)).observe(app,{childList:true,subtree:true});window.addEventListener('focus',()=>{cache=null;document.querySelector('.today-center')?.remove();enhance()});window.addEventListener('solobizkit:workspace-updated',()=>{cache=null;document.querySelector('.today-center')?.remove();enhance()});enhance();