import { getDataOwnerId, getSession, getWorkspaceContext, loadWorkspace, supabase } from './backend.js';

const app=document.querySelector('#app');
const pageTitle=document.querySelector('#pageTitle');
let cache=null,context=null,dataOwner=null,session=null;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]);
const today=()=>new Date().toISOString().slice(0,10);
function customerName(data,id){return data.customers.find(c=>c.id===id)?.name||'Customer'}
function taskHref(task){if(task.related_type==='estimate'&&task.related_id)return`/pro/estimates/?estimate=${encodeURIComponent(task.related_id)}`;if(task.related_type==='invoice'&&task.related_id)return`/pro/?view=invoices&invoice=${encodeURIComponent(task.related_id)}`;if(task.related_type==='deal'&&task.related_id)return'/pro/pipeline/';if(task.customer_id)return`/pro/?view=customers&customer=${encodeURIComponent(task.customer_id)}`;return'/pro/pipeline/'}
async function syncAutomation(){if(!context?.canWrite)return;const{error}=await supabase.rpc('sync_crm_automation');if(error)console.warn('Today CRM automation sync skipped',error)}
async function data(force=false){session||=await getSession();if(!session?.user?.id)return null;if(force||!cache){context=await getWorkspaceContext(true);dataOwner=await getDataOwnerId();await syncAutomation();const workspace=await loadWorkspace(session.user.id);const[tasks,deals]=await Promise.all([supabase.from('crm_tasks').select('*').eq('user_id',dataOwner).is('completed_at',null).order('priority',{ascending:false}).order('due_date',{ascending:true}),supabase.from('crm_deals').select('id,customer_id,title,stage,lead_score,score_reasons,last_engaged_at').eq('user_id',dataOwner).not('stage','in','(won,lost)').order('lead_score',{ascending:false}).limit(8)]);if(tasks.error)throw tasks.error;if(deals.error)throw deals.error;cache={...workspace,tasks:tasks.data||[],deals:deals.data||[]}}return cache}
function dueItems(d){return d.tasks.map(task=>({kind:'task',id:task.id,tone:task.priority==='high'||task.due_date<today()?'danger':'normal',title:task.title,detail:`${customerName(d,task.customer_id)} · ${task.due_date<today()?'Overdue':'Due'} ${task.due_date}`,href:taskHref(task)})).sort((a,b)=>(a.tone==='danger'?-1:1)-(b.tone==='danger'?-1:1)).slice(0,8)}
async function completeTask(id){if(!context?.canWrite)return;const{error}=await supabase.from('crm_tasks').update({completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',dataOwner);if(error)throw error;cache=null;document.querySelector('.today-center')?.remove();enhance()}
function inject(d){if(pageTitle?.textContent!=='Dashboard'||app.querySelector('.today-center'))return;const target=app.querySelector('.dashboard-v2')||app.querySelector('.stats');if(!target)return;const items=dueItems(d);const dueTasks=d.tasks.filter(t=>t.due_date<=today()).length;const highPriority=d.tasks.filter(t=>t.priority==='high').length;const hot=d.deals.filter(deal=>Number(deal.lead_score||0)>=75);const warm=d.deals.filter(deal=>Number(deal.lead_score||0)>=45&&Number(deal.lead_score||0)<75);const wrap=document.createElement('section');wrap.className='card today-center';wrap.innerHTML=`<div class="card-head"><div><p class="eyebrow">TODAY</p><h2>Your day</h2><p class="muted">Automatic follow-ups and the opportunities most worth your attention.</p></div><a class="mini-btn" href="/pro/pipeline/">Open pipeline</a></div><div class="today-stats"><span><b>${dueTasks}</b> tasks due</span><span><b>${highPriority}</b> high priority</span><span><b>${hot.length}</b> hot leads</span><span><b>${warm.length}</b> warm leads</span></div>${hot.length?`<div class="today-hot"><strong>Hot opportunities</strong>${hot.slice(0,3).map(deal=>`<a href="/pro/pipeline/"><span>${esc(deal.title)}</span><b>${Number(deal.lead_score||0)}/100</b></a>`).join('')}</div>`:''}<div class="today-list">${items.length?items.map(i=>`<div class="today-item ${i.tone}"><a href="${i.href}"><strong>${esc(i.title)}</strong><small>${esc(i.detail)}</small></a>${context?.canWrite?`<button class="mini-btn" data-complete-task="${i.id}">Done</button>`:''}</div>`).join(''):'<div class="empty compact-empty">Nothing needs attention today.</div>'}</div>`;target.insertAdjacentElement('afterend',wrap);wrap.querySelectorAll('[data-complete-task]').forEach(b=>b.onclick=()=>completeTask(b.dataset.completeTask).catch(e=>alert(e.message||'Could not complete task.')))}
function style(){if(document.querySelector('#todayCenterStyle'))return;const s=document.createElement('style');s.id='todayCenterStyle';s.textContent='.today-center{margin-top:18px}.today-center .card-head{align-items:flex-start}.today-stats{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.today-stats span{padding:8px 10px;border-radius:999px;background:#f4f7fb;font-size:12px;color:#5f6c80}.today-stats b{color:#111827}.today-hot{display:grid;gap:7px;margin:0 0 14px;padding:12px;border-radius:13px;background:#fff8f8;border:1px solid #f3d1d1}.today-hot>strong{font-size:12px}.today-hot a{display:flex;align-items:center;justify-content:space-between;gap:10px;text-decoration:none;color:inherit;font-size:12px}.today-hot a b{color:#a61b1b}.today-list{display:grid;gap:8px}.today-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:12px;border:1px solid #e8ebf0;border-radius:12px}.today-item.danger{border-color:#f4c7c7;background:#fffafa}.today-item a{text-decoration:none;color:inherit}.today-item strong,.today-item small{display:block}.today-item small{margin-top:3px;color:#6b7280;font-size:12px}@media(max-width:600px){.today-item{grid-template-columns:1fr}.today-item .mini-btn{width:100%}}';document.head.appendChild(s)}
async function enhance(){style();if(pageTitle?.textContent!=='Dashboard')return;try{const d=await data();if(d)inject(d)}catch(e){console.warn('Today center skipped',e)}}
new MutationObserver(()=>requestAnimationFrame(enhance)).observe(app,{childList:true,subtree:true});window.addEventListener('focus',()=>{cache=null;document.querySelector('.today-center')?.remove();enhance()});window.addEventListener('solobizkit:workspace-updated',()=>{cache=null;document.querySelector('.today-center')?.remove();enhance()});enhance();