import { getSession, loadWorkspace, saveCustomer, supabase } from '../backend.js';

const app=document.querySelector('#app');
const shell=document.querySelector('#shell');
const authActions=document.querySelector('#authActions');
const modal=document.querySelector('#formModal');
const formEditor=document.querySelector('#formEditor');
const formModalTitle=document.querySelector('#formModalTitle');
const formModalBody=document.querySelector('#formModalBody');
const newFormBtn=document.querySelector('#newForm');
const importBtn=document.querySelector('#importCsv');
const exportBtn=document.querySelector('#exportCsv');
const csvInput=document.querySelector('#csvInput');
let session=null,subscription=null,workspace=null,forms=[],submissions=[],editingForm=null;

function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]);}
function hasPro(){return ['active','trialing'].includes(String(subscription?.status||'').toLowerCase())&&String(subscription?.plan||'').toLowerCase()==='pro';}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2200);}
function copy(text){return navigator.clipboard?.writeText(text).catch(()=>{});}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
function download(name,type,text){const blob=new Blob(['\ufeff'+text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'){if(quoted&&next==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';}else cell+=ch;}row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows;}
function normalizeHeader(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');}

async function load(){session=await getSession();if(!session?.user?.id){renderAuth();return;}const data=await loadWorkspace(session.user.id);workspace=data;subscription=data.subscription;shell.classList.remove('signed-out');authActions.innerHTML=`<span class="account-chip"><strong>${esc(session.user.email||'Account')}</strong><small>${hasPro()?'PRO':'ACCOUNT'}</small></span>`;if(!hasPro()){renderPaywall();return;}const [f,s]=await Promise.all([supabase.from('lead_forms').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}),supabase.from('lead_submissions').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(100)]);if(f.error)throw f.error;if(s.error)throw s.error;forms=f.data||[];submissions=s.data||[];render();}

function renderAuth(){shell.classList.add('signed-out');app.innerHTML='<div class="auth-stage"><section class="auth-card"><p class="eyebrow">SOLOBIZKIT PRO</p><h2>Sign in from the main Pro workspace.</h2><p class="muted auth-copy">Lead forms are part of SoloBizKit Pro.</p><a class="btn primary" href="/pro/">Open Pro</a></section></div>';}
function renderPaywall(){app.innerHTML='<div class="paywall-wrap"><section class="paywall-card"><p class="eyebrow">SOLOBIZKIT PRO</p><h2>Lead capture is a Pro feature.</h2><p class="paywall-lead">Create website forms that turn submissions directly into CRM leads with a follow-up date.</p><a class="btn primary" href="/pro/">Open subscription options</a></section></div>';}

function render(){const leads=workspace.customers.filter(c=>c.status!=='client');const due=leads.filter(c=>c.followUp&&c.followUp<=new Date().toISOString().slice(0,10));app.innerHTML=`<div class="lead-stat-grid"><div class="lead-stat"><span>Open leads</span><strong>${leads.length}</strong></div><div class="lead-stat"><span>Form submissions</span><strong>${submissions.length}</strong></div><div class="lead-stat"><span>Follow-ups due</span><strong>${due.length}</strong></div></div><div class="lead-grid"><section class="lead-card"><div class="lead-toolbar"><div><h2>Website lead forms</h2><p>Share a link or embed a form. New submissions become CRM leads automatically.</p></div></div><div class="lead-list">${forms.length?forms.map(formRow).join(''):'<div class="lead-empty">No lead forms yet. Create one and add it to your website.</div>'}</div></section><section class="lead-card"><div class="lead-toolbar"><div><h2>Recent submissions</h2><p>The latest website leads captured by your forms.</p></div></div><div class="submission-list">${submissions.length?submissions.map(submissionRow).join(''):'<div class="lead-empty">No submissions yet.</div>'}</div></section></div>`;bind();}

function formRow(f){const url=`${location.origin}/lead/?form=${encodeURIComponent(f.public_key)}`;const embed=`<iframe src="${url}" title="${esc(f.title)}" style="width:100%;min-height:620px;border:0;border-radius:16px" loading="lazy"></iframe>`;return `<div class="lead-form-row"><div class="lead-form-row-head"><div><strong>${esc(f.name)}</strong><div class="lead-meta"><span class="lead-badge ${f.active?'':'off'}">${f.active?'Active':'Paused'}</span><span>${esc(f.title)}</span></div></div></div><div class="lead-actions"><a class="primary-action" href="${url}" target="_blank" rel="noopener">Open form</a><button data-copy-link="${esc(url)}">Copy link</button><button data-copy-embed="${esc(embed)}">Copy embed</button><button data-edit-form="${f.id}">Edit</button><button data-toggle-form="${f.id}">${f.active?'Pause':'Activate'}</button></div><textarea class="lead-code" readonly>${esc(embed)}</textarea></div>`;}
function submissionRow(s){return `<div class="submission-row"><div class="submission-row-head"><div><strong>${esc(s.name)}</strong><div class="lead-meta"><span>${esc(s.company||s.email)}</span><span>${new Date(s.created_at).toLocaleString()}</span></div></div><span class="lead-source">${esc(s.source||'Website form')}</span></div>${s.message?`<div class="lead-message">${esc(s.message)}</div>`:''}<div class="lead-followup"><strong>CRM created automatically.</strong> Follow-up is scheduled for the next day.</div><div class="lead-actions"><a href="/pro/?view=customers">Open CRM</a>${s.email?`<a href="mailto:${esc(s.email)}">Reply by email</a>`:''}</div></div>`;}

function bind(){app.querySelectorAll('[data-copy-link]').forEach(b=>b.onclick=()=>copy(b.dataset.copyLink).then(()=>toast('Lead form link copied')));app.querySelectorAll('[data-copy-embed]').forEach(b=>b.onclick=()=>copy(b.dataset.copyEmbed).then(()=>toast('Embed code copied')));app.querySelectorAll('[data-edit-form]').forEach(b=>b.onclick=()=>openForm(b.dataset.editForm));app.querySelectorAll('[data-toggle-form]').forEach(b=>b.onclick=()=>toggleForm(b.dataset.toggleForm));}
function openForm(id=null){editingForm=forms.find(f=>f.id===id)||null;formModalTitle.textContent=editingForm?'Edit lead form':'New lead form';formModalBody.innerHTML=`<div class="field-grid"><div class="field"><label>Internal name</label><input class="input" name="name" required maxlength="80" value="${esc(editingForm?.name||'Website lead form')}"></div><div class="field"><label>Button label</label><input class="input" name="button_label" required maxlength="40" value="${esc(editingForm?.button_label||'Send request')}"></div><div class="field full"><label>Form title</label><input class="input" name="title" required maxlength="120" value="${esc(editingForm?.title||'Tell us about your project')}"></div><div class="field full"><label>Intro</label><textarea class="input" name="intro" maxlength="500">${esc(editingForm?.intro||'Share a few details and we will get back to you.')}</textarea></div><div class="field full"><label>Success message</label><input class="input" name="success_message" required maxlength="180" value="${esc(editingForm?.success_message||'Thanks — your request has been received.')}"></div></div>`;modal.showModal();}
async function toggleForm(id){const f=forms.find(x=>x.id===id);if(!f)return;const {error}=await supabase.from('lead_forms').update({active:!f.active,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',session.user.id);if(error)throw error;await load();}

formEditor.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(formEditor);const payload={user_id:session.user.id,name:String(fd.get('name')||'').trim(),title:String(fd.get('title')||'').trim(),intro:String(fd.get('intro')||'').trim()||null,button_label:String(fd.get('button_label')||'').trim(),success_message:String(fd.get('success_message')||'').trim(),updated_at:new Date().toISOString()};let result;if(editingForm)result=await supabase.from('lead_forms').update(payload).eq('id',editingForm.id).eq('user_id',session.user.id);else result=await supabase.from('lead_forms').insert(payload);if(result.error){alert(result.error.message);return;}modal.close();editingForm=null;await load();toast('Lead form saved');});
newFormBtn.onclick=()=>openForm();

exportBtn.onclick=()=>{const headers=['Name','Company','Email','Phone','Status','Lead source','Follow-up date','Next action','Notes'];const rows=workspace.customers.map(c=>[c.name,c.company,c.email,c.phone,c.status,c.source,c.followUp,c.nextAction,c.notes]);download('solobizkit-crm-export.csv','text/csv;charset=utf-8',[headers,...rows].map(r=>r.map(csvEscape).join(',')).join('\n'));toast('CRM export downloaded');};
importBtn.onclick=()=>csvInput.click();
csvInput.onchange=async()=>{const file=csvInput.files?.[0];if(!file)return;try{const rows=parseCsv(await file.text());if(rows.length<2)throw new Error('CSV has no data rows.');const headers=rows[0].map(normalizeHeader);const aliases={name:['name','customer','customer_name','contact','contact_name'],company:['company','business','organization'],email:['email','email_address'],phone:['phone','telephone','mobile'],status:['status','crm_status'],source:['source','lead_source'],followUp:['follow_up','followup','follow_up_date','next_follow_up'],nextAction:['next_action','action'],notes:['notes','note']};const idx={};for(const [key,list] of Object.entries(aliases))idx[key]=headers.findIndex(h=>list.includes(h));if(idx.name<0)throw new Error('CSV needs a Name column.');let imported=0;for(const row of rows.slice(1).slice(0,500)){const get=k=>idx[k]>=0?String(row[idx[k]]||'').trim():'';const name=get('name');if(!name)continue;const rawStatus=get('status').toLowerCase();const status=['client','won'].includes(rawStatus)?'client':['active','contacted','proposal'].includes(rawStatus)?'active':'lead';const customer={name,company:get('company'),email:get('email'),phone:get('phone'),status,notes:get('notes'),source:get('source')||'CSV import',followUp:get('followUp')||null,nextAction:get('nextAction')||'',persisted:false};await saveCustomer(session.user.id,customer);imported++;}csvInput.value='';await load();toast(`${imported} contact${imported===1?'':'s'} imported`);}catch(err){alert(err.message||'Could not import CSV.');}};

load().catch(err=>{console.error(err);app.innerHTML=`<div class="lead-empty">Could not load Leads: ${esc(err.message||'Unknown error')}</div>`;});
