const SUPABASE_URL='https://eaqddwqprhofpizbpziq.supabase.co';
const root=document.querySelector('#portal');
const token=new URLSearchParams(location.search).get('token')?.trim()||'';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=(v,c='USD')=>new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(Number(v||0));
const date=v=>v?new Intl.DateTimeFormat(undefined,{year:'numeric',month:'short',day:'numeric'}).format(new Date(`${v}T12:00:00`)):'—';
async function request(method='GET',body){const u=`${SUPABASE_URL}/functions/v1/customer-workspace${method==='GET'?`?token=${encodeURIComponent(token)}`:''}`;const r=await fetch(u,{method,headers:method==='POST'?{'content-type':'application/json'}:{accept:'application/json'},body:method==='POST'?JSON.stringify({token,...body}):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Customer portal is unavailable.');return d;}
async function load(){if(token.length<20)return error('Invalid customer link','Ask the business for a new secure link.');try{render(await request())}catch(e){error('Portal unavailable',e.message||'This link may have expired.')}}
function details(doc,type){const items=doc.items||[];return `<details class="doc-details"><summary>View details</summary><div class="doc-body"><div class="doc-meta"><span><b>Issued</b>${date(doc.issueDate)}</span><span><b>${type==='estimate'?'Valid until':'Due'}</b>${date(type==='estimate'?doc.validUntil:doc.dueDate)}</span></div>${items.length?`<div class="items">${items.map(i=>`<div class="item"><div><strong>${esc(i.description)}</strong><small>${Number(i.quantity||0)} × ${money(i.unitPrice,doc.currency)}${Number(i.taxRate||0)?` · ${Number(i.taxRate)}% tax`:''}</small></div><strong>${money(Number(i.quantity||0)*Number(i.unitPrice||0),doc.currency)}</strong></div>`).join('')}</div>`:'<div class="empty compact">No line items.</div>'}<div class="totals"><div><span>Subtotal</span><strong>${money(doc.subtotal,doc.currency)}</strong></div>${Number(doc.discountTotal||0)?`<div><span>Discount</span><strong>−${money(doc.discountTotal,doc.currency)}</strong></div>`:''}<div><span>Tax / VAT</span><strong>${money(doc.taxTotal,doc.currency)}</strong></div><div class="grand"><span>Total</span><strong>${money(doc.total,doc.currency)}</strong></div></div>${doc.notes?`<div class="notes"><b>Notes</b><p>${esc(doc.notes)}</p></div>`:''}</div></details>`;}
function estimateRow(e){const can=e.status==='sent';return `<article class="doc-card"><div class="row"><div class="main"><span class="label">Estimate</span><strong>${esc(e.number)}</strong></div><div><span class="label">Issued</span><strong>${date(e.issueDate)}</strong></div><div><span class="status ${esc(e.status)}">${esc(e.status)}</span></div><div><span class="label">Total</span><strong>${money(e.total,e.currency)}</strong></div><div class="actions">${can?`<button class="btn primary" data-estimate-decision="accepted" data-estimate-id="${esc(e.id)}">Accept</button><button class="btn danger" data-estimate-decision="declined" data-estimate-id="${esc(e.id)}">Decline</button>`:''}</div></div>${details(e,'estimate')}</article>`;}
function invoiceRow(i){const pay=i.paymentUrl&&i.status!=='paid'?`<a class="btn primary" href="${esc(i.paymentUrl)}" rel="noopener">Pay</a>`:'';return `<article class="doc-card"><div class="row"><div class="main"><span class="label">${i.documentType==='credit_note'?'Credit note':'Invoice'}</span><strong>${esc(i.number)}</strong></div><div><span class="label">Due</span><strong>${date(i.dueDate)}</strong></div><div><span class="status ${esc(i.status)}">${esc(i.status)}</span></div><div><span class="label">Total</span><strong>${money(i.total,i.currency)}</strong></div><div class="actions">${pay}</div></div>${details(i,'invoice')}</article>`;}
function render(data){const b=data.business||{},c=data.customer||{},invoices=data.invoices||[],estimates=data.estimates||[];const open=invoices.filter(x=>['sent','overdue'].includes(x.status));const currencies=[...new Set(open.map(x=>x.currency))];const due=currencies.length===1?money(open.reduce((s,x)=>s+Number(x.total||0),0),currencies[0]):`${open.length} open`;const logo=b.logo?`<img class="logo" src="${esc(b.logo)}" alt="">`:'<div class="mark">SB</div>';root.innerHTML=`<header><div class="brand">${logo}<div><p class="eyebrow">CUSTOMER PORTAL</p><h1>${esc(b.name||'Business')}</h1></div></div><div class="muted">Secure document history</div></header><div class="content"><div class="welcome"><div><p class="eyebrow">WELCOME</p><h2>${esc(c.name||'Customer')}</h2><p class="muted">Review estimates, invoices and payment status in one place.</p><div class="summary"><span class="chip">${estimates.length} estimates</span><span class="chip">${invoices.length} invoices</span><span class="chip">Amount due: ${esc(due)}</span></div></div></div><section class="section"><div class="section-head"><div><p class="eyebrow">ESTIMATES</p><h3>Quotes & approvals</h3></div></div>${estimates.length?`<div class="list">${estimates.map(estimateRow).join('')}</div>`:'<div class="empty">No estimates shared yet.</div>'}</section><section class="section"><div class="section-head"><div><p class="eyebrow">INVOICES</p><h3>Billing & payments</h3></div></div>${invoices.length?`<div class="list">${invoices.map(invoiceRow).join('')}</div>`:'<div class="empty">No invoices shared yet.</div>'}</section>${b.email||b.phone?`<div class="contact"><strong>Questions?</strong><br>${b.email?`<a href="mailto:${esc(b.email)}">${esc(b.email)}</a>`:''}${b.email&&b.phone?' · ':''}${esc(b.phone||'')}</div>`:''}</div>`;root.querySelectorAll('[data-estimate-decision]').forEach(btn=>btn.addEventListener('click',()=>decide(btn)));document.title=`${c.name||'Customer'} · ${b.name||'Customer portal'}`;}
async function decide(button){const decision=button.dataset.estimateDecision,estimateId=button.dataset.estimateId,label=button.textContent;button.disabled=true;button.textContent=decision==='accepted'?'Accepting…':'Saving…';try{await request('POST',{estimateId,decision});render(await request())}catch(e){button.disabled=false;button.textContent=label;alert(e.message||'Could not save your response.')}}
function error(title,message){root.innerHTML=`<div class="error"><h1>${esc(title)}</h1><p class="muted">${esc(message)}</p></div>`}
load();